/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2015-2-22: 16h:36m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef
struct {
ats_ptr_type atslab_c3nstroptref_loc ;
ats_ptr_type atslab_c3nstroptref_ref ;
} anairiats_rec_3 ;

typedef
struct {
ats_ptr_type atslab_h3ypo_loc ;
ats_ptr_type atslab_h3ypo_node ;
} anairiats_rec_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_c3nstr_loc ;
ats_ptr_type atslab_c3nstr_kind ;
ats_ptr_type atslab_c3nstr_node ;
} anairiats_rec_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPOprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPObind_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPOeqeq_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRitmlst_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMsvar_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMhypo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMsVar_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMcnstr_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMcnstr_ref_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMdisj_5) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_newline) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cstset_vt_listize_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2varset_vt_listize_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2cst_long) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2var_long) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2Var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp) (ats_ptr_type) ;
ATSextern_fun(anairiats_rec_1, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_mapgen_scst_svar) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type auxmain_4 (ats_ptr_type arg0) ;
static
ats_ptr_type auxmain_6 (ats_ptr_type arg0) ;
static
ats_void_type loop_10 (ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 4054(line=165, offs=3) -- 4889(line=199, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp1 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2var (tmp1) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMsvar"), tmp2) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp3 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (tmp3) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMhypo"), tmp4) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp5 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp6 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2Var (tmp5) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMsVar"), tmp6) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp7 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp8 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr (tmp7) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMcnstr"), tmp8) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp9 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp10 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_3, tmp9), atslab_c3nstroptref_loc) ;
tmp11 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_3, tmp9), atslab_c3nstroptref_ref) ;
tmp12 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp10) ;
tmp14 = ats_ptrget_mac(ats_ptr_type, tmp11) ;
tmp13 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (tmp14) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("S3ITMcnstr_ref"), tmp12, tmp13) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
// if (((ats_sum_ptr_type)arg0)->tag != 5) { ats_deadcode_failure_handle () ; }
__ats_lab_5_1:
tmp15 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp16 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (tmp15) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMdisj"), tmp16) ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 4969(line=205, offs=3) -- 5016(line=205, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst:
tmp17 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) ;
return (tmp17) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 5049(line=208, offs=3) -- 5101(line=208, offs=55)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp18) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst:
tmp18 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) ;
return (tmp18) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 5172(line=216, offs=5) -- 6028(line=254, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_4 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab_auxmain_4:
tmp21 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_h3ypo_node) ;
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp21)->tag != 0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_2, tmp21, atslab_0) ;
tmp23 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp (tmp22) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("H3YPOprop"), tmp23) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp21)->tag != 1) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp24 = ats_caselptrlab_mac(anairiats_sum_5, tmp21, atslab_0) ;
tmp25 = ats_caselptrlab_mac(anairiats_sum_5, tmp21, atslab_1) ;
tmp26 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2var (tmp24) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp (tmp25) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("H3YPObind"), tmp26, tmp27) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
// if (((ats_sum_ptr_type)tmp21)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_8_1:
tmp28 = ats_caselptrlab_mac(anairiats_sum_5, tmp21, atslab_0) ;
tmp29 = ats_caselptrlab_mac(anairiats_sum_5, tmp21, atslab_1) ;
tmp30 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp (tmp28) ;
tmp31 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp (tmp29) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("H3YPOeqeq"), tmp30, tmp31) ;
break ;
} while (0) ;
return (tmp20) ;
} /* end of [auxmain_4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 5152(line=214, offs=3) -- 6201(line=262, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo:
tmp32 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_4, arg0), atslab_h3ypo_loc) ;
tmp33 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp32) ;
tmp34 = auxmain_4 (arg0) ;
tmp19 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("h3ypo_loc"), tmp33, ATSstrcst("h3ypo_node"), tmp34) ;
return (tmp19) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6297(line=270, offs=5) -- 6599(line=285, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_6 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab_auxmain_6:
tmp37 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, arg0), atslab_c3nstr_node) ;
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp37)->tag != 0) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp38 = ats_caselptrlab_mac(anairiats_sum_2, tmp37, atslab_0) ;
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize1_s2exp (tmp38) ;
tmp36 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3NSTRprop"), tmp39) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
// if (((ats_sum_ptr_type)tmp37)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_10_1:
tmp40 = ats_caselptrlab_mac(anairiats_sum_2, tmp37, atslab_0) ;
tmp41 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (tmp40) ;
tmp36 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3NSTRitmlst"), tmp41) ;
break ;
} while (0) ;
return (tmp36) ;
} /* end of [auxmain_6] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6277(line=268, offs=3) -- 6775(line=293, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr:
tmp42 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, arg0), atslab_c3nstr_loc) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp42) ;
tmp44 = auxmain_6 (arg0) ;
tmp35 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstr_loc"), tmp43, ATSstrcst("c3nstr_node"), tmp44) ;
return (tmp35) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6855(line=299, offs=3) -- 6903(line=299, offs=51)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt:
tmp45 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr) ;
return (tmp45) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 4893(line=177, offs=7) -- 5015(line=178, offs=73)
*/
ATSstaticdec()
ats_void_type
loop_10 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;

__ats_lab_loop_10:
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp56 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp56 ;
goto __ats_lab_loop_10 ; // tail call
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
break ;
} while (0) ;
return /* (tmp55) */ ;
} /* end of [loop_10] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 4875(line=176, offs=14) -- 5054(line=182, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp54) ;

__ats_lab_list_vt_free_01499_ats_ptr_type:
/* tmp54 = */ loop_10 (arg0) ;
return /* (tmp54) */ ;
} /* end of [list_vt_free_01499_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6982(line=306, offs=3) -- 7919(line=347, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp46) ;
ATSlocal (anairiats_rec_1, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
// ATSlocal_void (tmp53) ;
ATSlocal (ats_ptr_type, tmp57) ;
// ATSlocal_void (tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
// ATSlocal_void (tmp60) ;
// ATSlocal_void (tmp61) ;
// ATSlocal_void (tmp62) ;
// ATSlocal_void (tmp63) ;
// ATSlocal_void (tmp64) ;
// ATSlocal_void (tmp65) ;
// ATSlocal_void (tmp66) ;
// ATSlocal_void (tmp67) ;
// ATSlocal_void (tmp68) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export:
tmp47 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_mapgen_scst_svar (arg1) ;
tmp48 = ats_select_mac(tmp47, atslab_0) ;
tmp49 = ats_select_mac(tmp47, atslab_1) ;
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cstset_vt_listize_free (tmp48) ;
tmp51 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2varset_vt_listize_free (tmp49) ;
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_castfn_mac(ats_ptr_type, tmp50), &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2cst_long) ;
/* tmp53 = */ list_vt_free_01499_ats_ptr_type (tmp50) ;
tmp57 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_castfn_mac(ats_ptr_type, tmp51), &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__jsonize_s2var_long) ;
/* tmp58 = */ list_vt_free_01499_ats_ptr_type (tmp51) ;
tmp59 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__jsonize_c3nstr (arg1) ;
/* tmp60 = */ atspre_fprint_string (arg0, ATSstrcst("{\n\"s2cstmap\":\n")) ;
/* tmp61 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp52) ;
/* tmp62 = */ atspre_fprint_newline (arg0) ;
/* tmp63 = */ atspre_fprint_string (arg0, ATSstrcst(",\n\"s2varmap\":\n")) ;
/* tmp64 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp57) ;
/* tmp65 = */ atspre_fprint_newline (arg0) ;
/* tmp66 = */ atspre_fprint_string (arg0, ATSstrcst(",\n\"c3nstrbody\":\n")) ;
/* tmp67 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp59) ;
/* tmp68 = */ atspre_fprint_string (arg0, ATSstrcst("\n}")) ;
/* tmp46 = */ atspre_fprint_newline (arg0) ;
return /* (tmp46) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_synent2_jsonize_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_constraint3_jsonize_dats.c] */
