/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-11-5:  2h:37m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_d3exp_loc ;
ats_ptr_type atslab_d3exp_type ;
ats_ptr_type atslab_d3exp_node ;
} anairiats_rec_1 ;

typedef
struct {
ats_ptr_type atslab_d2exp_loc ;
ats_ptr_type atslab_d2exp_node ;
ats_ptr_type atslab_d2exp_type ;
} anairiats_rec_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_5 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_8 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_9 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_11 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_12 ;

typedef
struct {
ats_ptr_type atslab_l0ab_loc ;
ats_ptr_type atslab_l0ab_lab ;
} anairiats_rec_13 ;

typedef
struct {
ats_ptr_type atslab_s2exp_srt ;
ats_ptr_type atslab_s2exp_node ;
} anairiats_rec_14 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_15 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOclo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__DL0ABELED_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__SLABELED_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Erefarg_27) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eint_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ebool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Echar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Efloat_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Estring_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ei0nt_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ec0har_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ef0loat_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Es0tring_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eempty_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ecstsp_15) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eextval_16) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elst_32) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Etup_33) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Erec_34) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eseq_35) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eassgn_40) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Earrpsz_43) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_dyn_50) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elaminit_dyn_51) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_met_52) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_sta_53) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Efix_54) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eann_type_64) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eann_seff_65) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eann_funclo_66) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eerrexp_67) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__T3E_d3exp_trdn_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__D23Ed2exp_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__D23Ed3exp_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_print_newline) () ;
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_print_string) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, patsopt_prerrf_ifdebug) (ats_ptr_type, ...) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__print_location) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__prerr_location) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_t0ype) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_vt0ype) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_fun_srt) (ats_ptr_type, ats_ptr_type, ats_int_type, ats_ptr_type, ats_int_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_metfun) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_tytup) (ats_int_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_tyrec) (ats_int_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_uni) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_t0ype_err) () ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__prerr_s2exp) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_nil) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_all) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__fpprint_s2exp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_nonlin) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2rt_prf_lin_fc) (ats_ptr_type, ats_bool_type, ats_bool_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_error_2esats__prerr_the_staerrlst) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_bool_t0ype) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_int_t0ype) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_char_t0ype) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_string_type) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_double_t0ype) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_void_t0ype) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_arrpsz_vt0ype_int_vt0ype) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_list_t0ype_int_type) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_list_vt0ype_int_vtype) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp3_2esats__d3exp_get_type) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, patsopt_d3exp_set_type) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_solve_2esats__s2hnf_tyleq_solve) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__the_trans3errlst_add) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__p2atlst_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_funclo_of_d2exp) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_s2eff_of_d2exp) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2explst_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__labd2explst_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23exp_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23explst_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_trdn_arg) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__i0nt_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__f0loat_syn_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__cstsp_syn_type) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__s2exp_Var_make_srt) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__d3exp_open_and_add) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body) (ats_ptr_type, ats_ptr_type, ats_int_type, ats_int_type, ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type prerr_FILENAME_02061_ () ;
static
ats_int_type loop_7 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type list_length_01409_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type loop_9 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_last_01406_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type loop_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_15 (ats_ptr_type arg0) ;
static
ats_void_type prerr_error3_loc_02067_ (ats_ptr_type arg0) ;
static
ats_ptr_type aux_18 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type f_23 (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 1608(line=48, offs=18) -- 1637(line=48, offs=47)
*/
ATSstaticdec()
ats_void_type
prerr_FILENAME_02061_ () {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_prerr_FILENAME_02061_:
/* tmp0 = */ atspre_prerr_string (ATSstrcst("pats_trans3_util")) ;
return /* (tmp0) */ ;
} /* end of [prerr_FILENAME_02061_] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 2259(line=91, offs=3) -- 2522(line=105, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__fshowtype_d3exp (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
// ATSlocal_void (tmp4) ;
// ATSlocal_void (tmp5) ;
// ATSlocal_void (tmp6) ;
// ATSlocal_void (tmp7) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__fshowtype_d3exp:
tmp2 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d3exp_loc) ;
tmp3 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp3_2esats__d3exp_get_type (arg0) ;
/* tmp4 = */ atspre_print_string (ATSstrcst("**SHOWTYPE**(")) ;
/* tmp5 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__print_location (tmp2) ;
/* tmp6 = */ atspre_print_string (ATSstrcst("): ")) ;
/* tmp7 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__fpprint_s2exp (stdout, tmp3) ;
/* tmp1 = */ atspre_print_newline () ;
return /* (tmp1) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__fshowtype_d3exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 2607(line=111, offs=3) -- 2763(line=116, offs=14)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_funclo_of_d2exp (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_funclo_of_d2exp:
tmp9 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp9)->tag != 66) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp10 = ats_caselptrlab_mac(anairiats_sum_3, tmp9, atslab_0) ;
tmp11 = ats_caselptrlab_mac(anairiats_sum_3, tmp9, atslab_1) ;
ats_ptrget_mac(ats_ptr_type, arg1) = tmp11 ;
tmp8 = tmp10 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp8 = arg0 ;
break ;
} while (0) ;
return (tmp8) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_funclo_of_d2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 2853(line=123, offs=3) -- 3230(line=137, offs=8)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_s2eff_of_d2exp (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_s2eff_of_d2exp:
tmp13 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp13)->tag != 50) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
ats_ptrget_mac(ats_ptr_type, arg1) = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_nil ;
tmp12 = arg0 ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp13)->tag != 51) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
ats_ptrget_mac(ats_ptr_type, arg1) = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_nil ;
tmp12 = arg0 ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp13)->tag != 53) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
ats_ptrget_mac(ats_ptr_type, arg1) = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_nil ;
tmp12 = arg0 ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp13)->tag != 65) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp14 = ats_caselptrlab_mac(anairiats_sum_3, tmp13, atslab_0) ;
tmp15 = ats_caselptrlab_mac(anairiats_sum_3, tmp13, atslab_1) ;
ats_ptrget_mac(ats_ptr_type, arg1) = tmp15 ;
tmp12 = tmp14 ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
__ats_lab_6_1:
ats_ptrget_mac(ats_ptr_type, arg1) = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2eff_all ;
tmp12 = arg0 ;
break ;
} while (0) ;
return (tmp12) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_s2eff_of_d2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 3510(line=153, offs=1) -- 4010(line=167, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_int_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_bool_type, tmp21) ;
ATSlocal (ats_bool_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body:
/* ats_ptr_type tmp17 ; */
tmp17 = arg1 ;
tmp18 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__p2atlst_syn_type (arg4) ;
tmp19 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type (arg5) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_funclo_of_d2exp (arg5, (&tmp17)) ;
tmp21 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf (tmp19) ;
tmp23 = atspre_gt_int_int (arg2, 0) ;
if (tmp23) {
tmp22 = ats_true_bool ;
} else {
tmp22 = ats_false_bool ;
} /* end of [if] */
/* ats_ptr_type tmp24 ; */
tmp25 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_s2eff_of_d2exp (tmp20, (&tmp24)) ;
tmp26 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2rt_prf_lin_fc (arg0, tmp21, tmp22, tmp17) ;
tmp16 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_fun_srt (tmp26, tmp17, arg2, tmp24, arg3, tmp18, tmp19) ;
return (tmp16) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51781(line=1842, offs=7) -- 51921(line=1845, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_7 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_int_type, tmp45) ;

__ats_lab_loop_7:
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
tmp45 = atspre_isucc (arg1) ;
arg0 = tmp44 ;
arg1 = tmp45 ;
goto __ats_lab_loop_7 ; // tail call
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_24_1:
tmp43 = arg1 ;
break ;
} while (0) ;
return (tmp43) ;
} /* end of [loop_7] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51764(line=1841, offs=13) -- 52005(line=1849, offs=4)
*/
ATSstaticdec()
ats_int_type
list_length_01409_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp42) ;

__ats_lab_list_length_01409_ats_ptr_type:
tmp42 = loop_7 (arg0, 0) ;
return (tmp42) ;
} /* end of [list_length_01409_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51232(line=1817, offs=5) -- 51354(line=1819, offs=58)
*/
ATSstaticdec()
ats_ptr_type
loop_9 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab_loop_9:
do {
/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp59 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp60 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
arg0 = tmp59 ;
arg1 = tmp60 ;
goto __ats_lab_loop_9 ; // tail call
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_30_1:
tmp58 = arg0 ;
break ;
} while (0) ;
return (tmp58) ;
} /* end of [loop_9] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51194(line=1813, offs=11) -- 51390(line=1823, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_last_01406_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;

__ats_lab_list_last_01406_ats_ptr_type:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp61 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_0) ;
tmp62 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
tmp57 = loop_9 (tmp61, tmp62) ;
return (tmp57) ;
} /* end of [list_last_01406_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 4098(line=173, offs=3) -- 7103(line=291, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_int_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_bool_type, tmp40) ;
ATSlocal (ats_int_type, tmp41) ;
ATSlocal (ats_bool_type, tmp46) ;
ATSlocal (ats_int_type, tmp47) ;
ATSlocal (ats_int_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_int_type, tmp51) ;
ATSlocal (ats_int_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_int_type, tmp67) ;
ATSlocal (ats_int_type, tmp68) ;
ATSlocal (ats_int_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_int_type, tmp73) ;
ATSlocal (ats_int_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type:
tmp28 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg0), atslab_d2exp_loc) ;
tmp29 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp29)->tag != 2) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_int_t0ype () ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp29)->tag != 4) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_bool_t0ype () ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp29)->tag != 5) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_char_t0ype () ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp29)->tag != 7) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_string_type () ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp29)->tag != 6) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_double_t0ype () ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp29)->tag != 8) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp30 = ats_caselptrlab_mac(anairiats_sum_4, tmp29, atslab_0) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__i0nt_syn_type (tmp30) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp29)->tag != 9) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_char_t0ype () ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp29)->tag != 11) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_string_type () ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp29)->tag != 10) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp31 = ats_caselptrlab_mac(anairiats_sum_4, tmp29, atslab_0) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__f0loat_syn_type (tmp31) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp29)->tag != 15) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_4, tmp29, atslab_0) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__cstsp_syn_type (arg0, tmp32) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp29)->tag != 14) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_void_t0ype () ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)tmp29)->tag != 16) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp33 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_0) ;
tmp27 = tmp33 ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp29)->tag != 40) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_void_t0ype () ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)tmp29)->tag != 32) { goto __ats_lab_25_0 ; }
__ats_lab_20_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_5, tmp29, atslab_0) ;
tmp35 = ats_caselptrlab_mac(anairiats_sum_5, tmp29, atslab_1) ;
tmp36 = ats_caselptrlab_mac(anairiats_sum_5, tmp29, atslab_2) ;
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (tmp35 == (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp38 = ats_caselptrlab_mac(anairiats_sum_6, tmp35, atslab_0) ;
tmp37 = tmp38 ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (tmp35 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp40 = atspre_eq_int_int (tmp34, 0) ;
if (tmp40) {
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_t0ype ;
} else {
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_vt0ype ;
} /* end of [if] */
tmp37 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__s2exp_Var_make_srt (tmp28, tmp39) ;
break ;
} while (0) ;
tmp41 = list_length_01409_ats_ptr_type (tmp36) ;
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_nonlin (tmp37) ;
if (tmp46) {
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_list_t0ype_int_type (tmp37, tmp41) ;
} else {
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_list_vt0ype_int_vtype (tmp37, tmp41) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp29)->tag != 33) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp47 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_0) ;
tmp48 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_1) ;
tmp49 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_2) ;
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2explst_syn_type (tmp49) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_tytup (tmp47, tmp48, tmp50) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp29)->tag != 34) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp51 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_0) ;
tmp52 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_1) ;
tmp53 = ats_caselptrlab_mac(anairiats_sum_8, tmp29, atslab_2) ;
tmp54 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__labd2explst_syn_type (tmp53) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_tyrec (tmp51, tmp52, tmp54) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)tmp29)->tag != 35) { goto __ats_lab_32_0 ; }
__ats_lab_27_1:
tmp55 = ats_caselptrlab_mac(anairiats_sum_4, tmp29, atslab_0) ;
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (tmp55 == (ats_sum_ptr_type)0) { goto __ats_lab_31_0 ; }
__ats_lab_28_1:
tmp56 = list_last_01406_ats_ptr_type (tmp55) ;
arg0 = tmp56 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type ; // tail call
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
// if (tmp55 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_31_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_void_t0ype () ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp29)->tag != 43) { goto __ats_lab_35_0 ; }
__ats_lab_32_1:
tmp63 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_0) ;
tmp64 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_1) ;
do {
/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (tmp63 == (ats_sum_ptr_type)0) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
tmp66 = ats_caselptrlab_mac(anairiats_sum_6, tmp63, atslab_0) ;
tmp65 = tmp66 ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
// if (tmp63 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_34_1:
tmp65 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__s2exp_Var_make_srt (tmp28, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_t0ype) ;
break ;
} while (0) ;
tmp67 = list_length_01409_ats_ptr_type (tmp64) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2exp_arrpsz_vt0ype_int_vt0ype (tmp65, tmp67) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp29)->tag != 50) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp68 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_0) ;
tmp69 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_1) ;
tmp70 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_2) ;
tmp71 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_3) ;
tmp72 = (ats_sum_ptr_type)0 ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body (tmp28, tmp72, tmp68, tmp69, tmp70, tmp71) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)tmp29)->tag != 51) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp73 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_0) ;
tmp74 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_1) ;
tmp75 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_2) ;
tmp76 = ats_caselptrlab_mac(anairiats_sum_9, tmp29, atslab_3) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_10)) ;
ats_selptrset_mac(anairiats_sum_10, tmp77, atslab_0, 0) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__d2exp_syn_type_arg_body (tmp28, tmp77, tmp73, tmp74, tmp75, tmp76) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp29)->tag != 53) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_11, tmp29, atslab_0) ;
tmp79 = ats_caselptrlab_mac(anairiats_sum_11, tmp29, atslab_1) ;
tmp80 = ats_caselptrlab_mac(anairiats_sum_11, tmp29, atslab_2) ;
tmp81 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type (tmp80) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_uni (tmp78, tmp79, tmp81) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp29)->tag != 52) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_11, tmp29, atslab_1) ;
tmp83 = ats_caselptrlab_mac(anairiats_sum_11, tmp29, atslab_2) ;
tmp84 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type (tmp83) ;
tmp85 = (ats_sum_ptr_type)0 ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_metfun (tmp85, tmp82, tmp84) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (((ats_sum_ptr_type)tmp29)->tag != 54) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_5, tmp29, atslab_2) ;
arg0 = tmp86 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type ; // tail call
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (((ats_sum_ptr_type)tmp29)->tag != 64) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
tmp87 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_1) ;
tmp27 = tmp87 ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp29)->tag != 65) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp88 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_0) ;
arg0 = tmp88 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type ; // tail call
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (((ats_sum_ptr_type)tmp29)->tag != 66) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp89 = ats_caselptrlab_mac(anairiats_sum_3, tmp29, atslab_0) ;
arg0 = tmp89 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type ; // tail call
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (((ats_sum_ptr_type)tmp29)->tag != 67) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_t0ype_err () ;
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
__ats_lab_44_1:
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__s2exp_Var_make_srt (tmp28, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_t0ype) ;
break ;
} while (0) ;
return (tmp27) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52519(line=1874, offs=5) -- 52952(line=1891, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;

__ats_lab_loop_13:
do {
/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_46_0 ; }
__ats_lab_45_1:
tmp95 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_0) ;
tmp96 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
tmp97 = ((ats_ptr_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp95, arg3) ;
tmp98 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp98, atslab_0, tmp97) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp98 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp99 = &ats_caselptrlab_mac(anairiats_sum_7, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp96 ;
arg1 = arg1 ;
arg2 = tmp99 ;
arg3 = arg3 ;
goto __ats_lab_loop_13 ; // tail call
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_46_1:
tmp100 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp100 ;
break ;
} while (0) ;
return /* (tmp94) */ ;
} /* end of [loop_13] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52444(line=1870, offs=3) -- 53099(line=1899, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp101) ;
// ATSlocal_void (tmp102) ;

__ats_lab_list_map_funenv_01411_ats_ptr_type_ats_ptr_type:
/* ats_ptr_type tmp101 ; */
/* tmp102 = */ loop_13 (arg0, arg1, (&tmp101), arg2) ;
tmp93 = tmp101 ;
return (tmp93) ;
} /* end of [list_map_funenv_01411_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 53173(line=1904, offs=3) -- 53424(line=1911, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp92) ;

__ats_lab_list_map_fun_01412_ats_ptr_type_ats_ptr_type:
tmp92 = list_map_funenv_01411_ats_ptr_type_ats_ptr_type (arg0, ats_castfn_mac(ats_ptr_type, arg1), atspre_null_ptr) ;
return (tmp92) ;
} /* end of [list_map_fun_01412_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7162(line=295, offs=3) -- 7207(line=295, offs=48)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2explst_syn_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2explst_syn_type:
tmp91 = list_map_fun_01412_ats_ptr_type_ats_ptr_type (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type) ;
tmp90 = ats_castfn_mac(ats_ptr_type, tmp91) ;
return (tmp90) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2explst_syn_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7287(line=300, offs=6) -- 7436(line=306, offs=6)
*/
ATSstaticdec()
ats_ptr_type
f_15 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;

__ats_lab_f_15:

tmp105 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_0) ;
tmp106 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
tmp107 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, tmp105), atslab_l0ab_lab) ;
tmp108 = (ats_sum_ptr_type)0 ;
tmp109 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d2exp_syn_type (tmp106) ;
tmp104 = ATS_MALLOC(sizeof(anairiats_sum_12)) ;
ats_selptrset_mac(anairiats_sum_12, tmp104, atslab_0, tmp107) ;
ats_selptrset_mac(anairiats_sum_12, tmp104, atslab_1, tmp108) ;
ats_selptrset_mac(anairiats_sum_12, tmp104, atslab_2, tmp109) ;
return (tmp104) ;
} /* end of [f_15] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7271(line=299, offs=22) -- 7486(line=309, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__labd2explst_syn_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp110) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__labd2explst_syn_type:
tmp110 = list_map_fun_01412_ats_ptr_type_ats_ptr_type (arg0, &f_15) ;
tmp103 = ats_castfn_mac(ats_ptr_type, tmp110) ;
return (tmp103) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__labd2explst_syn_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7563(line=314, offs=13) -- 7631(line=315, offs=52)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23exp_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp111) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23exp_free:
do {
/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
ATS_FREE(arg0) ;
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
// if (((ats_sum_ptr_type)arg0)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_48_1:
ATS_FREE(arg0) ;
break ;
} while (0) ;
return /* (tmp111) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23exp_free] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7682(line=319, offs=16) -- 7794(line=321, offs=26)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23explst_free (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
// ATSlocal_void (tmp115) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23explst_free:
do {
/* branch: __ats_lab_49 */
__ats_lab_49_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_50_0 ; }
__ats_lab_49_1:
tmp113 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_0) ;
tmp114 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
ATS_FREE(arg0) ;
/* tmp115 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23exp_free (tmp113) ;
arg0 = tmp114 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23explst_free ; // tail call
break ;

/* branch: __ats_lab_50 */
__ats_lab_50_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_50_1:
break ;
} while (0) ;
return /* (tmp112) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d23explst_free] */

/*
// /home/hwxi/research/Postiats/git/src/pats_errmsg.dats: 2182(line=76, offs=18) -- 2241(line=79, offs=2)
*/
ATSstaticdec()
ats_void_type
prerr_error3_loc_02067_ (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp126) ;
// ATSlocal_void (tmp127) ;

__ats_lab_prerr_error3_loc_02067_:
/* tmp127 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__prerr_location (arg0) ;
/* tmp126 = */ atspre_prerr_string (ATSstrcst(": error(3)")) ;
return /* (tmp126) */ ;
} /* end of [prerr_error3_loc_02067_] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 7855(line=328, offs=5) -- 8690(line=357, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_18 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_int_type, tmp122) ;
// ATSlocal_void (tmp123) ;
ATSlocal (ats_bool_type, tmp124) ;
// ATSlocal_void (tmp125) ;
// ATSlocal_void (tmp128) ;
// ATSlocal_void (tmp129) ;
// ATSlocal_void (tmp130) ;
// ATSlocal_void (tmp131) ;
// ATSlocal_void (tmp132) ;
// ATSlocal_void (tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
// ATSlocal_void (tmp135) ;

__ats_lab_aux_18:
tmp117 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d3exp_loc) ;
tmp118 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d3exp_type) ;
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (tmp118) ;
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (tmp119) ;
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (arg1) ;
tmp122 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_solve_2esats__s2hnf_tyleq_solve (tmp117, tmp119, arg1) ;
tmp124 = atspre_neq_int_int (tmp122, 0) ;
if (tmp124) {
/* tmp125 = */ prerr_error3_loc_02067_ (tmp117) ;
/* tmp128 = */ patsopt_prerrf_ifdebug (ATSstrcst(": [%s]: %s"), ATSstrcst("/home/hwxi/research/Postiats/git/src/pats_trans3_util.dats"), ATSstrcst("d3exp_trdn")) ;
/* tmp129 = */ atspre_prerr_string (ATSstrcst(": the dynamic expression cannot be assigned the type [")) ;
/* tmp130 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__prerr_s2exp (tmp121) ;
/* tmp131 = */ atspre_prerr_string (ATSstrcst("].")) ;
/* tmp132 = */ atspre_prerr_newline () ;
/* tmp133 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_error_2esats__prerr_the_staerrlst () ;
tmp134 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp134)->tag = 22 ;
ats_selptrset_mac(anairiats_sum_3, tmp134, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp134, atslab_1, tmp121) ;
/* tmp123 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__the_trans3errlst_add (tmp134) ;
} else {
/* empty */
} /* end of [if] */
/* tmp135 = */ patsopt_d3exp_set_type (arg0, tmp121) ;
tmp116 = arg0 ;
return (tmp116) ;
} /* end of [aux_18] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 8753(line=363, offs=3) -- 8920(line=374, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp136) ;
ATSlocal (ats_ptr_type, tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn:
tmp137 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (arg1) ;
tmp138 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_14, arg1), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_51 */
__ats_lab_51_0:
if (((ats_sum_ptr_type)tmp138)->tag != 27) { goto __ats_lab_52_0 ; }
__ats_lab_51_1:
tmp139 = ats_caselptrlab_mac(anairiats_sum_15, tmp138, atslab_1) ;
arg0 = arg0 ;
arg1 = tmp139 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn ; // tail call
break ;

/* branch: __ats_lab_52 */
__ats_lab_52_0:
__ats_lab_52_1:
tmp136 = aux_18 (arg0, tmp137) ;
break ;
} while (0) ;
return (tmp136) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 9022(line=382, offs=3) -- 9365(line=393, offs=31)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_trdn_arg (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_trdn_arg:
do {
/* branch: __ats_lab_53 */
__ats_lab_53_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_56_0 ; }
__ats_lab_53_1:
tmp141 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_0) ;
tmp142 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
do {
/* branch: __ats_lab_54 */
__ats_lab_54_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_55_0 ; }
__ats_lab_54_1:
tmp143 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp144 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp145 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3exp_trdn (tmp141, tmp143) ;
tmp146 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_trdn_arg (tmp142, tmp144) ;
tmp140 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp140, atslab_0, tmp145) ;
ats_selptrset_mac(anairiats_sum_7, tmp140, atslab_1, tmp146) ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_55_1:
tmp140 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_56 */
__ats_lab_56_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_56_1:
tmp140 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp140) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_trdn_arg] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 9463(line=401, offs=5) -- 9548(line=403, offs=4)
*/
ATSstaticdec()
ats_ptr_type
f_23 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp148) ;
// ATSlocal_void (tmp149) ;

__ats_lab_f_23:
/* tmp149 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__d3exp_open_and_add (arg0) ;
tmp148 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp3_2esats__d3exp_get_type (arg0) ;
return (tmp148) ;
} /* end of [f_23] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_util.dats: 9445(line=399, offs=18) -- 9613(line=407, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_get_ind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp150) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_get_ind:
tmp150 = list_map_fun_01412_ats_ptr_type_ats_ptr_type (arg0, &f_23) ;
tmp147 = ats_castfn_mac(ats_ptr_type, tmp150) ;
return (tmp147) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__d3explst_get_ind] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_error_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp3_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_solve_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_syntax_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_error_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp3_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_solve_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_trans3_util_dats.c] */
