/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-9-19: 14h:40m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_d2exp_loc ;
ats_ptr_type atslab_d2exp_node ;
ats_ptr_type atslab_d2exp_type ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_p1at_loc ;
ats_ptr_type atslab_p1at_node ;
} anairiats_rec_6 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_8 ;

typedef
struct {
ats_ptr_type atslab_d1exp_loc ;
ats_ptr_type atslab_d1exp_node ;
} anairiats_rec_9 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_11 ;

typedef
struct {
ats_ptr_type atslab_d2lab_loc ;
ats_ptr_type atslab_d2lab_node ;
ats_ptr_type atslab_d2lab_overld ;
} anairiats_rec_12 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__P1Tlist_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_dyn_48) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_met_50) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_ana_51) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_syn_52) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Evar_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eint_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ebool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Echar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Estring_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ei0nt_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ec0har_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Es0tring_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Etop_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eselab_36) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eviewat_38) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ederef_39) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Earrsub_42) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eexist_49) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_dyn_50) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_sta_53) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALderef_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_lin_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_mut_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALarrsub_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALviewat_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALnone_5) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__location_combine) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_selab) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_int_type loop_3 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type list_length_01409_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_bool_type __ats_fun_4 (ats_int_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_4_closure_make (ats_int_type env0) ;
static
ats_bool_type __ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type app_6 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_filter_funenv_01337_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_filter_vclo_01339_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_ptr_type d2exp_d2var_lvalize_9 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_int_type p1at_arity_11 (ats_ptr_type arg0) ;
static
ats_bool_type loop1_13 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type loop2_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_bool_type loop1_13_0loop2_14 (ats_int_type arg0, ...) ;
static
ats_bool_type aritest_12 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_18 (ats_ptr_type arg0) ;
static
ats_ptr_type aux2_19 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type revapp_24 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_vt_reverse_append_01506_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type list_vt_reverse_01505_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type aux_21 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 1859(line=67, offs=3) -- 2310(line=95, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_bool_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst:
tmp1 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp1)->tag != 1) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_caselptrlab_mac(anairiats_sum_2, tmp1, atslab_0) ;
tmp3 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (tmp2) ;
if (tmp3) {
tmp0 = ats_false_bool ;
} else {
tmp0 = ats_true_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp1)->tag != 50) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp1)->tag != 53) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp1)->tag != 2) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp1)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp1)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp1)->tag != 7) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp1)->tag != 8) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp1)->tag != 9) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp1)->tag != 11) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp1)->tag != 12) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp1)->tag != 49) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp4 = ats_caselptrlab_mac(anairiats_sum_3, tmp1, atslab_1) ;
arg0 = tmp4 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst ; // tail call
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
__ats_lab_12_1:
tmp0 = ats_false_bool ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51781(line=1842, offs=7) -- 51921(line=1845, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_3 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;

__ats_lab_loop_3:
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp9 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp10 = atspre_isucc (arg1) ;
arg0 = tmp9 ;
arg1 = tmp10 ;
goto __ats_lab_loop_3 ; // tail call
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_14_1:
tmp8 = arg1 ;
break ;
} while (0) ;
return (tmp8) ;
} /* end of [loop_3] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51764(line=1841, offs=13) -- 52005(line=1849, offs=4)
*/
ATSstaticdec()
ats_int_type
list_length_01409_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp7) ;

__ats_lab_list_length_01409_ats_ptr_type:
tmp7 = loop_3 (arg0, 0) ;
return (tmp7) ;
} /* end of [list_length_01409_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2489(line=105, offs=18) -- 2578(line=107, offs=52)
*/
ATSstaticdec()
ats_bool_type
__ats_fun_4 (ats_int_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;

__ats_lab___ats_fun_4:
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full (arg0) ;
tmp13 = atspre_eq_int_int (tmp14, env0) ;
return (tmp13) ;
} /* end of [__ats_fun_4] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_4_closure_type ;

ats_bool_type
__ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return __ats_fun_4 (((__ats_fun_4_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_4_closure_init (__ats_fun_4_closure_type *p_clo, ats_int_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_4_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 21113(line=764, offs=6) -- 21259(line=768, offs=6)
*/
ATSstaticdec()
ats_bool_type
app_6 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp18) ;

__ats_lab_app_6:
tmp18 = ((ats_bool_type(*)(ats_clo_ptr_type, ats_ptr_type))(ats_closure_fun(arg1))) (arg1, arg0) ;
return (tmp18) ;
} /* end of [app_6] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19833(line=716, offs=7) -- 20397(line=733, offs=40)
*/
ATSstaticdec()
ats_void_type
loop_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab_loop_8:
do {
/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp21 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp22 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp23 = ((ats_bool_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp21, arg3) ;
if (tmp23) {
tmp24 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp24, atslab_0, tmp21) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp24 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp25 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp22 ;
arg1 = arg1 ;
arg2 = tmp25 ;
arg3 = arg3 ;
goto __ats_lab_loop_8 ; // tail call
} else {
arg0 = tmp22 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_8 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_16_1:
tmp26 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp26 ;
break ;
} while (0) ;
return /* (tmp20) */ ;
} /* end of [loop_8] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19800(line=714, offs=24) -- 20566(line=744, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_funenv_01337_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;

__ats_lab_list_filter_funenv_01337_ats_ptr_type:
/* ats_ptr_type tmp27 ; */
/* tmp28 = */ loop_8 (arg0, arg1, (&tmp27), arg2) ;
tmp19 = tmp27 ;
return (tmp19) ;
} /* end of [list_filter_funenv_01337_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 20978(line=760, offs=19) -- 21434(line=775, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_vclo_01339_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_list_filter_vclo_01339_ats_ptr_type:
tmp17 = list_filter_funenv_01337_ats_ptr_type (arg0, &app_6, arg1) ;
return (tmp17) ;
} /* end of [list_filter_vclo_01339_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2395(line=101, offs=3) -- 2822(line=115, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_int_type, tmp6) ;
ATSlocal (ats_bool_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (__ats_fun_4_closure_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity:
tmp6 = list_length_01409_ats_ptr_type (arg0) ;
tmp11 = atspre_igte (tmp6, 2) ;
if (tmp11) {
/* ats_ptr_type tmp12 ; */
tmp12 = &(tmp15) ;
__ats_fun_4_closure_init (tmp12, arg1) ; // closure initialization
tmp16 = list_filter_vclo_01339_ats_ptr_type (arg0, tmp12) ;
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (ats_castfn_mac(ats_ptr_type, tmp16) == (ats_sum_ptr_type)0) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp5 = ats_castfn_mac(ats_ptr_type, tmp16) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
// if (ats_castfn_mac(ats_ptr_type, tmp16) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_18_1:
tmp5 = arg0 ;
break ;
} while (0) ;
} else {
tmp5 = arg0 ;
} /* end of [if] */
return (tmp5) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2887(line=122, offs=1) -- 3127(line=129, offs=27)
*/
ATSstaticdec()
ats_ptr_type
d2exp_d2var_lvalize_9 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_bool_type, tmp30) ;
ATSlocal (ats_bool_type, tmp31) ;

__ats_lab_d2exp_d2var_lvalize_9:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
__ats_lab_19_1:
tmp30 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear (arg1) ;
if (!tmp30) { goto __ats_lab_20_1 ; }
tmp29 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp29)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp29, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp29, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
__ats_lab_20_1:
tmp31 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (arg1) ;
if (!tmp31) { goto __ats_lab_21_1 ; }
tmp29 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp29)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_3, tmp29, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp29, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
__ats_lab_21_1:
tmp29 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp29)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp29, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp29) ;
} /* end of [d2exp_d2var_lvalize_9] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3217(line=136, offs=3) -- 3871(line=164, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize:
tmp33 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp33)->tag != 1) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_2, tmp33, atslab_0) ;
tmp35 = (ats_sum_ptr_type)0 ;
tmp32 = d2exp_d2var_lvalize_9 (arg0, tmp34, tmp35) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp33)->tag != 39) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp36 = ats_caselptrlab_mac(anairiats_sum_2, tmp33, atslab_0) ;
tmp37 = (ats_sum_ptr_type)0 ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp32)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp32, atslab_0, tmp36) ;
ats_selptrset_mac(anairiats_sum_3, tmp32, atslab_1, tmp37) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp33)->tag != 36) { goto __ats_lab_28_0 ; }
__ats_lab_24_1:
tmp38 = ats_caselptrlab_mac(anairiats_sum_3, tmp33, atslab_0) ;
tmp39 = ats_caselptrlab_mac(anairiats_sum_3, tmp33, atslab_1) ;
tmp40 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp38), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp40)->tag != 1) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp41 = ats_caselptrlab_mac(anairiats_sum_2, tmp40, atslab_0) ;
tmp32 = d2exp_d2var_lvalize_9 (arg0, tmp41, tmp39) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp40)->tag != 39) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp42 = ats_caselptrlab_mac(anairiats_sum_2, tmp40, atslab_0) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp32)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp32, atslab_0, tmp42) ;
ats_selptrset_mac(anairiats_sum_3, tmp32, atslab_1, tmp39) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
__ats_lab_27_1:
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp32)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp32, atslab_0, arg0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)tmp33)->tag != 38) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp43 = ats_caselptrlab_mac(anairiats_sum_2, tmp33, atslab_0) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp32)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_2, tmp32, atslab_0, tmp43) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp33)->tag != 42) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_5, tmp33, atslab_0) ;
tmp45 = ats_caselptrlab_mac(anairiats_sum_5, tmp33, atslab_1) ;
tmp46 = ats_caselptrlab_mac(anairiats_sum_5, tmp33, atslab_2) ;
tmp47 = ats_caselptrlab_mac(anairiats_sum_5, tmp33, atslab_3) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp32)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_5, tmp32, atslab_0, tmp44) ;
ats_selptrset_mac(anairiats_sum_5, tmp32, atslab_1, tmp45) ;
ats_selptrset_mac(anairiats_sum_5, tmp32, atslab_2, tmp46) ;
ats_selptrset_mac(anairiats_sum_5, tmp32, atslab_3, tmp47) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
__ats_lab_30_1:
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp32)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp32, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp32) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3980(line=174, offs=4) -- 4095(line=179, offs=2)
*/
ATSstaticdec()
ats_int_type
p1at_arity_11 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;

__ats_lab_p1at_arity_11:
tmp49 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, arg0), atslab_p1at_node) ;
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp49)->tag != 14) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp50 = ats_caselptrlab_mac(anairiats_sum_7, tmp49, atslab_1) ;
tmp48 = list_length_01409_ats_ptr_type (tmp50) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
__ats_lab_32_1:
tmp48 = 1 ;
break ;
} while (0) ;
return (tmp48) ;
} /* end of [p1at_arity_11] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4179(line=183, offs=7) -- 4316(line=189, offs=46)
*/
ATSstaticdec()
ats_bool_type
loop1_13 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp70) ;

tmp70 = loop1_13_0loop2_14 (0, arg0, arg1) ;
return (tmp70) ;
} /* end of [loop1_13] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4343(line=191, offs=7) -- 4750(line=204, offs=32)
*/
ATSstaticdec()
ats_bool_type
loop2_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp71) ;

tmp71 = loop1_13_0loop2_14 (1, arg0, arg1, arg2) ;
return (tmp71) ;
} /* end of [loop2_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4179(line=183, offs=7) -- 4750(line=204, offs=32)
*/
ATSstaticdec()
ats_bool_type
loop1_13_0loop2_14 (ats_int_type arg0, ...) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_int_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_bool_type, tmp57) ;
ATSlocal (ats_int_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_bool_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_bool_type, tmp64) ;
ATSlocal (ats_int_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_bool_type, tmp69) ;

va_list funarg ;

switch (arg0) {
case 0:
va_start(funarg, arg0) ;
tmp52 = va_arg(funarg, ats_ptr_type) ;
tmp53 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop1_13 ;

case 1:
va_start(funarg, arg0) ;
tmp54 = va_arg(funarg, ats_ptr_type) ;
tmp55 = va_arg(funarg, ats_int_type) ;
tmp56 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop2_14 ;

default: exit(1) ; /* deadcode */
} /* end of switch */

ATSlocal (va_list, arg1) ;
va_start(arg1, arg0) ;

__ats_lab_loop1_13:
do {
/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (tmp53 != (ats_sum_ptr_type)0) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
tmp57 = ats_true_bool ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
// if (tmp53 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_34_1:
tmp58 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_0) ;
tmp59 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_1) ;
tmp54 = tmp52 ;
tmp55 = tmp58 ;
tmp56 = tmp59 ;
goto __ats_lab_loop2_14 ; // tail call
break ;
} while (0) ;
return tmp57 ;

__ats_lab_loop2_14:
tmp61 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_9, tmp54), atslab_d1exp_node) ;
do {
/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp61)->tag != 48) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp62 = ats_caselptrlab_mac(anairiats_sum_10, tmp61, atslab_1) ;
tmp63 = ats_caselptrlab_mac(anairiats_sum_10, tmp61, atslab_2) ;
tmp65 = p1at_arity_11 (tmp62) ;
tmp64 = atspre_eq_int_int (tmp55, tmp65) ;
if (tmp64) {
tmp52 = tmp63 ;
tmp53 = tmp56 ;
goto __ats_lab_loop1_13 ; // tail call
} else {
tmp60 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)tmp61)->tag != 50) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp66 = ats_caselptrlab_mac(anairiats_sum_11, tmp61, atslab_2) ;
tmp54 = tmp66 ;
tmp55 = tmp55 ;
tmp56 = tmp56 ;
goto __ats_lab_loop2_14 ; // tail call
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp61)->tag != 51) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp67 = ats_caselptrlab_mac(anairiats_sum_11, tmp61, atslab_2) ;
tmp54 = tmp67 ;
tmp55 = tmp55 ;
tmp56 = tmp56 ;
goto __ats_lab_loop2_14 ; // tail call
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp61)->tag != 52) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp68 = ats_caselptrlab_mac(anairiats_sum_11, tmp61, atslab_2) ;
tmp54 = tmp68 ;
tmp55 = tmp55 ;
tmp56 = tmp56 ;
goto __ats_lab_loop2_14 ; // tail call
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
__ats_lab_39_1:
tmp60 = ats_false_bool ;
break ;
} while (0) ;
return tmp60 ;

return (tmp69) ;
} /* end of [loop1_13_0loop2_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4126(line=181, offs=4) -- 4795(line=208, offs=4)
*/
ATSstaticdec()
ats_bool_type
aritest_12 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp51) ;

__ats_lab_aritest_12:
tmp51 = loop1_13 (arg0, arg1) ;
return (tmp51) ;
} /* end of [aritest_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4865(line=213, offs=17) -- 4941(line=215, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def:
tmp73 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst (arg0) ;
tmp72 = aritest_12 (arg1, tmp73) ;
return (tmp72) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5067(line=225, offs=5) -- 5202(line=231, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_18 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;

__ats_lab_aux_18:
do {
/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
tmp75 = (ats_sum_ptr_type)0 ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_41_1:
tmp76 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp77 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp75 = aux2_19 (tmp76, tmp77) ;
break ;
} while (0) ;
return (tmp75) ;
} /* end of [aux_18] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5229(line=233, offs=5) -- 5375(line=241, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux2_19 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;

__ats_lab_aux2_19:
do {
/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp78 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_12, arg0), atslab_d2lab_overld) ;
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_43_1:
tmp79 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_0) ;
tmp80 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_1) ;
arg0 = tmp79 ;
arg1 = tmp80 ;
goto __ats_lab_aux2_19 ; // tail call
break ;
} while (0) ;
return (tmp78) ;
} /* end of [aux2_19] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5047(line=223, offs=3) -- 5487(line=248, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld:
tmp81 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (((ats_sum_ptr_type)tmp81)->tag != 36) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_3, tmp81, atslab_1) ;
tmp74 = aux_18 (tmp82) ;
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
__ats_lab_45_1:
tmp74 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp74) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7889(line=308, offs=7) -- 8174(line=317, offs=28)
*/
ATSstaticdec()
ats_ptr_type
revapp_24 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;

__ats_lab_revapp_24:
do {
/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
tmp98 = &ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp99 = ats_ptrget_mac(ats_ptr_type, tmp98) ;
ats_ptrget_mac(ats_ptr_type, tmp98) = arg1 ;
tmp100 = arg0 ;
arg0 = tmp99 ;
arg1 = tmp100 ;
goto __ats_lab_revapp_24 ; // tail call
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_48_1:
tmp97 = arg1 ;
break ;
} while (0) ;
return (tmp97) ;
} /* end of [revapp_24] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7770(line=303, offs=24) -- 8220(line=321, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_vt_reverse_append_01506_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp96) ;

__ats_lab_list_vt_reverse_append_01506_ats_ptr_type:
tmp96 = revapp_24 (arg0, arg1) ;
return (tmp96) ;
} /* end of [list_vt_reverse_append_01506_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 7652(line=298, offs=17) -- 7704(line=299, offs=46)
*/
ATSstaticdec()
ats_ptr_type
list_vt_reverse_01505_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp101) ;

__ats_lab_list_vt_reverse_01505_ats_ptr_type:
tmp101 = (ats_sum_ptr_type)0 ;
tmp95 = list_vt_reverse_append_01506_ats_ptr_type (arg0, tmp101) ;
return (tmp95) ;
} /* end of [list_vt_reverse_01505_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5684(line=261, offs=5) -- 6135(line=283, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_21 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;

__ats_lab_aux_21:
do {
/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (arg3 != (ats_sum_ptr_type)0) { goto __ats_lab_49_0 ; }
__ats_lab_46_1:
tmp91 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_loc) ;
tmp92 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_12, arg1), atslab_d2lab_loc) ;
tmp90 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__location_combine (tmp91, tmp92) ;
tmp93 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp93, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_4, tmp93, atslab_1, arg4) ;
tmp94 = list_vt_reverse_01505_ats_ptr_type (tmp93) ;
tmp89 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_selab (tmp90, arg0, ats_castfn_mac(ats_ptr_type, tmp94)) ;
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
// if (arg3 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_49_1:
tmp102 = ats_caselptrlab_mac(anairiats_sum_4, arg3, atslab_0) ;
tmp103 = ats_caselptrlab_mac(anairiats_sum_4, arg3, atslab_1) ;
tmp104 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_1, arg4) ;
arg0 = arg0 ;
arg1 = arg2 ;
arg2 = tmp102 ;
arg3 = tmp103 ;
arg4 = tmp104 ;
goto __ats_lab_aux_21 ; // tail call
break ;
} while (0) ;
return (tmp89) ;
} /* end of [aux_21] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5579(line=254, offs=3) -- 6294(line=294, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root:
tmp84 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
if (((ats_sum_ptr_type)tmp84)->tag != 36) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5599(line=256, offs=5) -- 5639(line=257, offs=32)") ; }
tmp85 = ats_caselptrlab_mac(anairiats_sum_3, tmp84, atslab_0) ;
tmp86 = ats_caselptrlab_mac(anairiats_sum_3, tmp84, atslab_1) ;
if (tmp86 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 5647(line=259, offs=5) -- 5676(line=259, offs=34)") ; }
tmp87 = ats_caselptrlab_mac(anairiats_sum_4, tmp86, atslab_0) ;
tmp88 = ats_caselptrlab_mac(anairiats_sum_4, tmp86, atslab_1) ;
do {
/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (tmp88 != (ats_sum_ptr_type)0) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp83 = tmp85 ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
// if (tmp88 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_51_1:
tmp105 = ats_caselptrlab_mac(anairiats_sum_4, tmp88, atslab_0) ;
tmp106 = ats_caselptrlab_mac(anairiats_sum_4, tmp88, atslab_1) ;
tmp107 = (ats_sum_ptr_type)0 ;
tmp83 = aux_21 (tmp85, tmp87, tmp105, tmp106, tmp107) ;
break ;
} while (0) ;
return (tmp83) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_get_seloverld_root] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_dynexp2_util_dats.c] */
