/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-9-19: 14h:40m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "libc/CATS/string.cats"

#include "libc/CATS/errno.cats"

#include "libc/CATS/unistd.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_filename_givename ;
ats_ptr_type atslab_filename_partname ;
ats_ptr_type atslab_filename_fullname ;
} anairiats_rec_1 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_vt_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_newline) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_string_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, atspre_compare_string_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_char_type, atspre_string_get_char_at) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_make_substring) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_stringlst_concat) (ats_ptr_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_string_isnot_atend) (ats_ptr_type, ats_size_type) ;
ATSextern_val(ats_ptr_type, atspre_stropt_none) ;
ATSextern_fun(ats_bool_type, atspre_stropt_is_some) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_strptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprintf_exn) (ats_ptr_type, ats_ptr_type, ...) ;
ATSextern_fun(ats_bool_type, atspre_test_file_exists) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__eq_symbol_symbol) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_make_string) (ats_ptr_type) ;
ATSextern_fun(ats_char_type, patsopt_filename_theDirSep_get) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theParDir_get) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get) () ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_srchknd) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_partname) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, patsopt_filename_merge) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, patsopt_filename_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__eq_filename_filename) (ats_ptr_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_dummy) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_isnot_dummy) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_current) () ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_ppush) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_ppush) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__pkgsrcname_relocatize) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, patsopt_string_test_suffix) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atslib_getcwd0) () ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__sasp__the_pathlst_push_v = 0 ;
int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__sasp__the_filenamelst_push_v = 0 ;
int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__sasp__filename_type = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_dummy) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_stdin) ;

/* internal function declarations */
static
ats_char_type ptr0_get_01758_ats_char_type (ats_ptr_type arg0) ;
static
ats_ptr_type loop_5 (ats_ptr_type arg0, ats_int_type arg1, ats_char_type arg2, ats_char_type arg3) ;
static
ats_bool_type aux_19 (ats_ptr_type arg0, ats_size_type arg1, ats_char_type arg2) ;
static
ats_void_type loop1_23 (ats_char_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3, ats_ref_type arg4) ;
static
ats_void_type loop2_24 (ats_char_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3, ats_size_type arg4, ats_ref_type arg5) ;
static
ats_ptr_type loop_26 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type dirs_process_25 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;
static
ats_void_type loop_28 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type loop_28_closure_make (ats_ptr_type env0) ;
static
ats_void_type loop_28_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_fun_01499_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type __ats_fun_29 (ats_ref_type arg0) ;
static
ats_ptr_type partname_fullize_31 (ats_ptr_type arg0) ;
static
ats_ptr_type ref_01087_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type ref_make_elt_01088_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_bool_type loop_35 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type filename_occurs_34 (ats_ptr_type arg0) ;
static
ats_void_type loop_42 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type the_pathlst_get_43 () ;
static
ats_void_type the_pathlst_set_44 (ats_ptr_type arg0) ;
static
ats_ptr_type the_prepathlst_get_48 () ;
static
ats_void_type the_prepathlst_set_49 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_local_52 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_try_53 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux2_try_54 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type aux_try_pathlst_55 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_try_prepathlst_56 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_relative_57 (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp56) ;
ATSstatic (ats_ptr_type, statmp57) ;
ATSstatic (ats_ptr_type, statmp123) ;
ATSstatic (ats_ptr_type, statmp127) ;
ATSstatic (ats_ptr_type, statmp128) ;
ATSstatic (ats_ptr_type, statmp162) ;
ATSstatic (ats_ptr_type, statmp163) ;
ATSstatic (ats_ptr_type, statmp164) ;
ATSstatic (ats_ptr_type, statmp165) ;

/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2000(line=74, offs=25) -- 2014(line=74, offs=39)
*/
ATSglobaldec()
ats_char_type
patsopt_filename_theDirSep_get () {
/* local vardec */
ATSlocal (ats_char_type, tmp0) ;

__ats_lab_patsopt_filename_theDirSep_get:
tmp0 = '/' ;
return (tmp0) ;
} /* end of [patsopt_filename_theDirSep_get] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2039(line=75, offs=25) -- 2053(line=75, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get:
tmp1 = ATSstrcst("./") ;
return (tmp1) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2078(line=76, offs=25) -- 2092(line=76, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theParDir_get () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theParDir_get:
tmp2 = ATSstrcst("../") ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theParDir_get] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2267(line=92, offs=3) -- 2411(line=97, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_srchknd (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_size_type, tmp5) ;
ATSlocal (ats_bool_type, tmp6) ;
ATSlocal (ats_int_type, tmp7) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_srchknd:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get () ;
tmp5 = atspre_string_length (tmp4) ;
tmp7 = atslib_strncmp (arg0, tmp4, tmp5) ;
tmp6 = atspre_eq_int_int (tmp7, 0) ;
if (tmp6) {
tmp3 = 0 ;
} else {
tmp3 = 1 ;
} /* end of [if] */
return (tmp3) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_srchknd] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/unsafe.dats: 1763(line=50, offs=10) -- 1979(line=60, offs=2)
*/
ATSstaticdec()
ats_char_type
ptr0_get_01758_ats_char_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_char_type, tmp11) ;

__ats_lab_ptr0_get_01758_ats_char_type:
tmp11 = ats_ptrget_mac(ats_char_type, ats_castfn_mac(ats_ptr_type, arg0)) ;
return (tmp11) ;
} /* end of [ptr0_get_01758_ats_char_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2764(line=112, offs=5) -- 3095(line=130, offs=4)
*/
ATSstaticdec()
ats_ptr_type
loop_5 (ats_ptr_type arg0, ats_int_type arg1, ats_char_type arg2, ats_char_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_char_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_bool_type, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;
ATSlocal (ats_bool_type, tmp15) ;
ATSlocal (ats_bool_type, tmp16) ;
ATSlocal (ats_int_type, tmp17) ;
ATSlocal (ats_bool_type, tmp18) ;

__ats_lab_loop_5:
tmp10 = ptr0_get_01758_ats_char_type (arg0) ;
tmp12 = atspre_padd_size (arg0, sizeof(ats_char_type)) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
__ats_lab_0_1:
tmp13 = atspre_eq_char_char (tmp10, arg2) ;
if (!tmp13) { goto __ats_lab_1_1 ; }
tmp14 = atspre_add_int_int (arg1, 1) ;
arg0 = tmp12 ;
arg1 = tmp14 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_5 ; // tail call
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp15 = atspre_eq_char_char (tmp10, arg3) ;
if (!tmp15) { goto __ats_lab_2_1 ; }
tmp16 = atspre_gt_int_int (arg1, 1) ;
if (tmp16) {
tmp17 = atspre_sub_int_int (arg1, 1) ;
arg0 = tmp12 ;
arg1 = tmp17 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_5 ; // tail call
} else {
tmp9 = tmp12 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
__ats_lab_2_1:
tmp18 = atspre_neq_char_char (tmp10, '\000') ;
if (tmp18) {
arg0 = tmp12 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_5 ; // tail call
} else {
tmp9 = atspre_null_ptr ;
} /* end of [if] */
break ;
} while (0) ;
return (tmp9) ;
} /* end of [loop_5] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 2743(line=110, offs=3) -- 3617(line=155, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_char_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_bool_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_ptrdiff_type, tmp24) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl:
tmp19 = ptr0_get_01758_ats_char_type (ats_castfn_mac(ats_ptr_type, arg0)) ;
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp21 = atspre_eq_char_char (tmp19, '{') ;
if (!tmp21) { goto __ats_lab_4_1 ; }
tmp22 = atspre_padd_int (ats_castfn_mac(ats_ptr_type, arg0), 1) ;
tmp20 = loop_5 (tmp22, 1, tmp19, '}') ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
__ats_lab_4_1:
tmp20 = atspre_null_ptr ;
break ;
} while (0) ;
tmp23 = atspre_pgt (ats_castfn_mac(ats_ptr_type, tmp20), ats_castfn_mac(ats_ptr_type, ats_castfn_mac(ats_ptr_type, arg0))) ;
if (tmp23) {
tmp24 = atspre_pdiff (ats_castfn_mac(ats_ptr_type, tmp20), ats_castfn_mac(ats_ptr_type, ats_castfn_mac(ats_ptr_type, arg0))) ;
tmp8 = ats_castfn_mac(ats_int_type, tmp24) ;
} else {
tmp8 = -1 ;
} /* end of [if] */
return (tmp8) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 3880(line=170, offs=23) -- 3909(line=170, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_givename (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp25) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_givename:
tmp25 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_givename) ;
return (tmp25) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_givename] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 3942(line=172, offs=23) -- 3971(line=172, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_partname (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_partname:
tmp26 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_partname) ;
return (tmp26) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_partname] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 4004(line=174, offs=23) -- 4033(line=174, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_fullname (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp27) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_fullname:
tmp27 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_fullname) ;
return (tmp27) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_fullname] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 4341(line=193, offs=3) -- 4387(line=193, offs=49)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__print_filename_full (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp28) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__print_filename_full:
/* tmp28 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full (stdout, arg0) ;
return /* (tmp28) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__print_filename_full] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 4420(line=196, offs=3) -- 4466(line=196, offs=49)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__prerr_filename_full (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp29) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__prerr_filename_full:
/* tmp29 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full (stderr, arg0) ;
return /* (tmp29) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__prerr_filename_full] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 4500(line=199, offs=3) -- 4611(line=203, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full:
tmp32 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_filename_fullname) ;
tmp31 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (tmp32) ;
/* tmp30 = */ atspre_fprint_string (arg0, tmp31) ;
return /* (tmp30) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 4701(line=209, offs=3) -- 4976(line=222, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint2_filename_full (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_int_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_bool_type, tmp38) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint2_filename_full:
tmp34 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_filename_givename) ;
tmp35 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl (tmp34) ;
tmp37 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_filename_fullname) ;
tmp36 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (tmp37) ;
tmp38 = atspre_lt_int_int (tmp35, 0) ;
if (tmp38) {
/* tmp33 = */ atspre_fprint_string (arg0, tmp36) ;
} else {
/* tmp33 = */ atspre_fprintf_exn (arg0, ATSstrcst("%s(%s)"), tmp36, tmp34) ;
} /* end of [if] */
return /* (tmp33) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint2_filename_full] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5066(line=228, offs=3) -- 5120(line=228, offs=57)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__eq_filename_filename (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__eq_filename_filename:
tmp40 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_fullname) ;
tmp41 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_filename_fullname) ;
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp40, tmp41) ;
return (tmp39) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__eq_filename_filename] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5214(line=235, offs=3) -- 5378(line=240, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__compare_filename_filename (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__compare_filename_filename:
tmp44 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_fullname) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (tmp44) ;
tmp46 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_filename_fullname) ;
tmp45 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (tmp46) ;
tmp42 = atspre_compare_string_string (tmp43, tmp45) ;
return (tmp42) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__compare_filename_filename] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5649(line=257, offs=18) -- 5710(line=258, offs=54)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_sats (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_sats:
tmp48 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_partname) ;
tmp47 = patsopt_string_test_suffix (tmp48, ATSstrcst(".sats")) ;
return (tmp47) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_sats] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5738(line=260, offs=18) -- 5799(line=261, offs=54)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dats (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dats:
tmp50 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_partname) ;
tmp49 = patsopt_string_test_suffix (tmp50, ATSstrcst(".dats")) ;
return (tmp49) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dats] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5953(line=272, offs=6) -- 6113(line=276, offs=74)
*/
ATSstaticdec()
ats_bool_type
aux_19 (ats_ptr_type arg0, ats_size_type arg1, ats_char_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp52) ;
ATSlocal (ats_bool_type, tmp53) ;
ATSlocal (ats_char_type, tmp54) ;

__ats_lab_aux_19:
tmp53 = atspre_string_isnot_atend (arg0, arg1) ;
if (tmp53) {
tmp54 = atspre_string_get_char_at (arg0, arg1) ;
tmp52 = atspre_neq_char_char (tmp54, arg2) ;
} else {
tmp52 = ats_false_bool ;
} /* end of [if] */
return (tmp52) ;
} /* end of [aux_19] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 5934(line=271, offs=3) -- 6236(line=282, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp51) ;
ATSlocal (ats_char_type, tmp55) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative:
tmp55 = patsopt_filename_theDirSep_get () ;
tmp51 = aux_19 (ats_castfn_mac(ats_ptr_type, arg0), 0, tmp55) ;
return (tmp51) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 6644(line=301, offs=19) -- 6719(line=302, offs=68)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dummy (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp58) ;
ATSlocal (ats_bool_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dummy:
tmp60 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_fullname) ;
tmp59 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp60, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
if (tmp59) {
tmp58 = ats_true_bool ;
} else {
tmp58 = ats_false_bool ;
} /* end of [if] */
return (tmp58) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_is_dummy] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 6782(line=306, offs=22) -- 6857(line=307, offs=68)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_isnot_dummy (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp61) ;
ATSlocal (ats_bool_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_isnot_dummy:
tmp63 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_filename_fullname) ;
tmp62 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__eq_symbol_symbol (tmp63, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
if (tmp62) {
tmp61 = ats_false_bool ;
} else {
tmp61 = ats_true_bool ;
} /* end of [if] */
return (tmp61) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_isnot_dummy] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 7000(line=316, offs=7) -- 7204(line=322, offs=65)
*/
ATSstaticdec()
ats_void_type
loop1_23 (ats_char_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3, ats_ref_type arg4) {
/* local vardec */
// ATSlocal_void (tmp65) ;
ATSlocal (ats_bool_type, tmp66) ;

__ats_lab_loop1_23:
tmp66 = atspre_lt_size1_size1 (arg3, arg2) ;
if (tmp66) {
/* tmp65 = */ loop2_24 (arg0, arg1, arg2, arg3, arg3, arg4) ;
} else {
/* empty */
} /* end of [if] */
return /* (tmp65) */ ;
} /* end of [loop1_23] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 7211(line=323, offs=7) -- 8219(line=357, offs=8)
*/
ATSstaticdec()
ats_void_type
loop2_24 (ats_char_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3, ats_size_type arg4, ats_ref_type arg5) {
/* local vardec */
// ATSlocal_void (tmp67) ;
ATSlocal (ats_bool_type, tmp68) ;
ATSlocal (ats_bool_type, tmp69) ;
ATSlocal (ats_char_type, tmp70) ;
ATSlocal (ats_size_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_size_type, tmp73) ;
ATSlocal (ats_size_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_size_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_size_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;

__ats_lab_loop2_24:
tmp68 = atspre_lt_size1_size1 (arg4, arg2) ;
if (tmp68) {
tmp70 = atspre_string_get_char_at (arg1, arg4) ;
tmp69 = atspre_neq_char_char (tmp70, arg0) ;
if (tmp69) {
tmp71 = atspre_add_size1_int1 (arg4, 1) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
arg4 = tmp71 ;
arg5 = arg5 ;
goto __ats_lab_loop2_24 ; // tail call
} else {
tmp74 = atspre_sub_size1_size1 (arg4, arg3) ;
tmp73 = atspre_add_size1_int1 (tmp74, 1) ;
tmp72 = atspre_string_make_substring (arg1, arg3, tmp73) ;
tmp75 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp75, atslab_0, ats_castfn_mac(ats_ptr_type, tmp72)) ;
ats_selptrset_mac(anairiats_sum_2, tmp75, atslab_1, ats_ptrget_mac(ats_ptr_type, arg5)) ;
ats_ptrget_mac(ats_ptr_type, arg5) = tmp75 ;
tmp76 = atspre_add_size1_int1 (arg4, 1) ;
/* tmp67 = */ loop1_23 (arg0, arg1, arg2, tmp76, arg5) ;
} /* end of [if] */
} else {
tmp78 = atspre_sub_size1_size1 (arg4, arg3) ;
tmp77 = atspre_string_make_substring (arg1, arg3, tmp78) ;
tmp79 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp79, atslab_0, ats_castfn_mac(ats_ptr_type, tmp77)) ;
ats_selptrset_mac(anairiats_sum_2, tmp79, atslab_1, ats_ptrget_mac(ats_ptr_type, arg5)) ;
ats_ptrget_mac(ats_ptr_type, arg5) = tmp79 ;
} /* end of [if] */
return /* (tmp67) */ ;
} /* end of [loop2_24] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 9269(line=386, offs=13) -- 9748(line=398, offs=23)
*/
ATSstaticdec()
ats_ptr_type
loop_26 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_bool_type, tmp93) ;
ATSlocal (ats_size_type, tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_int_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;

__ats_lab_loop_26:
tmp93 = atspre_igt (arg1, 0) ;
if (tmp93) {
tmp94 = atspre_string_length (ats_castfn_mac(ats_ptr_type, arg0)) ;
tmp95 = atspre_string_make_substring (ats_castfn_mac(ats_ptr_type, arg0), 0, tmp94) ;
tmp96 = atspre_isub (arg1, 1) ;
tmp97 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp97, atslab_0, ats_castfn_mac(ats_ptr_type, tmp95)) ;
ats_selptrset_mac(anairiats_sum_2, tmp97, atslab_1, arg2) ;
arg0 = arg0 ;
arg1 = tmp96 ;
arg2 = tmp97 ;
goto __ats_lab_loop_26 ; // tail call
} else {
tmp92 = arg2 ;
} /* end of [if] */
return (tmp92) ;
} /* end of [loop_26] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 8376(line=363, offs=7) -- 9809(line=401, offs=8)
*/
ATSstaticdec()
ats_ptr_type
dirs_process_25 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_bool_type, tmp83) ;
// ATSlocal_void (tmp84) ;
ATSlocal (ats_bool_type, tmp85) ;
// ATSlocal_void (tmp86) ;
ATSlocal (ats_int_type, tmp87) ;
ATSlocal (ats_bool_type, tmp88) ;
// ATSlocal_void (tmp89) ;
ATSlocal (ats_int_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;

__ats_lab_dirs_process_25:
do {
/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (arg3 == (ats_sum_ptr_type)0) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp81 = ats_caselptrlab_mac(anairiats_sum_2, arg3, atslab_0) ;
tmp82 = ats_caselptrlab_mac(anairiats_sum_2, arg3, atslab_1) ;
ATS_FREE(arg3) ;
tmp83 = atspre_eq_string_string (ats_castfn_mac(ats_ptr_type, tmp81), arg0) ;
if (tmp83) {
/* tmp84 = */ atspre_strptr_free (tmp81) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = tmp82 ;
arg4 = arg4 ;
goto __ats_lab_dirs_process_25 ; // tail call
} else {
tmp85 = atspre_eq_string_string (ats_castfn_mac(ats_ptr_type, tmp81), arg1) ;
if (tmp85) {
/* tmp86 = */ atspre_strptr_free (tmp81) ;
tmp87 = atspre_iadd (arg2, 1) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = tmp87 ;
arg3 = tmp82 ;
arg4 = arg4 ;
goto __ats_lab_dirs_process_25 ; // tail call
} else {
tmp88 = atspre_igt (arg2, 0) ;
if (tmp88) {
/* tmp89 = */ atspre_strptr_free (tmp81) ;
tmp90 = atspre_isub (arg2, 1) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = tmp90 ;
arg3 = tmp82 ;
arg4 = arg4 ;
goto __ats_lab_dirs_process_25 ; // tail call
} else {
tmp91 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp91, atslab_0, tmp81) ;
ats_selptrset_mac(anairiats_sum_2, tmp91, atslab_1, arg4) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = 0 ;
arg3 = tmp82 ;
arg4 = tmp91 ;
goto __ats_lab_dirs_process_25 ; // tail call
} /* end of [if] */
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
// if (arg3 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_6_1:
tmp80 = loop_26 (arg1, arg2, arg4) ;
break ;
} while (0) ;
return (tmp80) ;
} /* end of [dirs_process_25] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 5132(line=186, offs=7) -- 5320(line=191, offs=28)
*/
ATSstaticdec()
ats_void_type
loop_28 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
// ATSlocal_void (tmp112) ;

__ats_lab_loop_28:
do {
/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp110 = &ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp111 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
/* tmp112 = */ ((ats_void_type(*)(ats_ref_type))env0) (tmp110) ;
ATS_FREE(arg0) ;
arg0 = tmp111 ;
goto __ats_lab_loop_28 ; // tail call
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_8_1:
break ;
} while (0) ;
return /* (tmp109) */ ;
} /* end of [loop_28] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} loop_28_closure_type ;

ats_void_type
loop_28_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
loop_28 (((loop_28_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
loop_28_closure_init (loop_28_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&loop_28_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
loop_28_closure_make (ats_ptr_type env0) {
loop_28_closure_type *p_clo = ATS_MALLOC(sizeof(loop_28_closure_type)) ;
loop_28_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list_vt.dats: 5111(line=185, offs=18) -- 5359(line=195, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_fun_01499_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp108) ;

__ats_lab_list_vt_free_fun_01499_ats_ptr_type:
/* tmp108 = */ loop_28 (arg1, arg0) ;
return /* (tmp108) */ ;
} /* end of [list_vt_free_fun_01499_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 10323(line=414, offs=45) -- 10347(line=414, offs=69)
*/
ATSstaticdec()
ats_void_type
__ats_fun_29 (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp113) ;

__ats_lab___ats_fun_29:
/* tmp113 = */ atspre_strptr_free (ats_ptrget_mac(ats_ptr_type, arg0)) ;
return /* (tmp113) */ ;
} /* end of [__ats_fun_29] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 6983(line=315, offs=19) -- 10375(line=418, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_char_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_size_type, tmp102) ;
// ATSlocal_void (tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
// ATSlocal_void (tmp107) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt:
tmp98 = patsopt_filename_theDirSep_get () ;
tmp99 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get () ;
tmp100 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theParDir_get () ;
/* ats_ptr_type tmp101 ; */
tmp101 = (ats_sum_ptr_type)0 ;
tmp102 = atspre_string_length (ats_castfn_mac(ats_ptr_type, arg0)) ;
/* tmp103 = */ loop1_23 (tmp98, ats_castfn_mac(ats_ptr_type, arg0), tmp102, 0, (&tmp101)) ;
tmp105 = (ats_sum_ptr_type)0 ;
tmp104 = dirs_process_25 (tmp99, tmp100, 0, tmp101, tmp105) ;
tmp101 = tmp104 ;
tmp106 = atspre_stringlst_concat (ats_castfn_mac(ats_ptr_type, tmp101)) ;
/* tmp107 = */ list_vt_free_fun_01499_ats_ptr_type (tmp101, &__ats_fun_29) ;
tmp64 = tmp106 ;
return (tmp64) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 10432(line=421, offs=16) -- 10480(line=422, offs=42)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize:
tmp115 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt (arg0) ;
tmp114 = ats_castfn_mac(ats_ptr_type, tmp115) ;
return (tmp114) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 10619(line=433, offs=5) -- 11014(line=448, offs=4)
*/
ATSstaticdec()
ats_ptr_type
partname_fullize_31 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_bool_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
// ATSlocal_void (tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;
// ATSlocal_void (tmp122) ;

__ats_lab_partname_fullize_31:
tmp117 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative (arg0) ;
if (tmp117) {
tmp118 = atslib_getcwd0 () ;
tmp119 = patsopt_filename_append (ats_castfn_mac(ats_ptr_type, tmp118), arg0) ;
/* tmp120 = */ atspre_strptr_free (tmp118) ;
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize (ats_castfn_mac(ats_ptr_type, tmp119)) ;
/* tmp122 = */ atspre_strptr_free (tmp119) ;
tmp116 = tmp121 ;
} else {
tmp116 = arg0 ;
} /* end of [if] */
return (tmp116) ;
} /* end of [partname_fullize_31] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01087_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;

__ats_lab_ref_01087_ats_ptr_type:
/* ats_ptr_type tmp126 ; */
tmp126 = arg0 ;
tmp125 = atspre_ref_make_elt_tsz ((&tmp126), sizeof(ats_ptr_type)) ;
return (tmp125) ;
} /* end of [ref_01087_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/reference.dats: 1994(line=62, offs=27) -- 2009(line=62, offs=42)
*/
ATSstaticdec()
ats_ptr_type
ref_make_elt_01088_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;

__ats_lab_ref_make_elt_01088_ats_ptr_type:
tmp124 = ref_01087_ats_ptr_type (arg0) ;
return (tmp124) ;
} /* end of [ref_make_elt_01088_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 11362(line=465, offs=7) -- 11733(line=476, offs=42)
*/
ATSstaticdec()
ats_bool_type
loop_35 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_bool_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;

__ats_lab_loop_35:
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp131 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp132 = &ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp133 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__eq_filename_filename (arg1, tmp131) ;
if (tmp133) {
tmp130 = ats_true_bool ;
} else {
tmp134 = ats_ptrget_mac(ats_ptr_type, tmp132) ;
arg0 = tmp134 ;
arg1 = arg1 ;
goto __ats_lab_loop_35 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_10_1:
tmp130 = ats_false_bool ;
break ;
} while (0) ;
return (tmp130) ;
} /* end of [loop_35] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 11311(line=463, offs=1) -- 11832(line=481, offs=4)
*/
ATSstaticdec()
ats_bool_type
filename_occurs_34 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;

__ats_lab_filename_occurs_34:
tmp135 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp127), atslab_1) ;
tmp136 = ats_ptrget_mac(ats_ptr_type, tmp135) ;
tmp129 = loop_35 (tmp136, arg0) ;
return (tmp129) ;
} /* end of [filename_occurs_34] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 11917(line=486, offs=22) -- 11935(line=486, offs=40)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_current () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp137) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_current:
tmp137 = ats_ptrget_mac(ats_ptr_type, statmp123) ;
return (tmp137) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_current] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 11969(line=490, offs=3) -- 12219(line=500, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_pop () {
/* local vardec */
// ATSlocal_void (tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_pop:
tmp139 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp127), atslab_1) ;
tmp140 = ats_ptrget_mac(ats_ptr_type, tmp139) ;
if (tmp140 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_filename.dats: 12101(line=494, offs=9) -- 12127(line=494, offs=35)") ; }
tmp141 = ats_caselptrlab_mac(anairiats_sum_2, tmp140, atslab_0) ;
tmp142 = ats_caselptrlab_mac(anairiats_sum_2, tmp140, atslab_1) ;
ATS_FREE(tmp140) ;
ats_ptrget_mac(ats_ptr_type, tmp139) = tmp142 ;
ats_ptrget_mac(ats_ptr_type, statmp123) = tmp141 ;
return /* (tmp138) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_pop] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 12284(line=503, offs=22) -- 12356(line=505, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp143) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push:
/* tmp143 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_ppush (arg0) ;
return /* (tmp143) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 12423(line=508, offs=23) -- 12603(line=515, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_ppush (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_ppush:
tmp145 = ats_ptrget_mac(ats_ptr_type, statmp123) ;
ats_ptrget_mac(ats_ptr_type, statmp123) = arg0 ;
tmp146 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp127), atslab_1) ;
tmp148 = ats_ptrget_mac(ats_ptr_type, tmp146) ;
tmp147 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp147, atslab_0, tmp145) ;
ats_selptrset_mac(anairiats_sum_2, tmp147, atslab_1, tmp148) ;
ats_ptrget_mac(ats_ptr_type, tmp146) = tmp147 ;
return /* (tmp144) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_ppush] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 12678(line=519, offs=3) -- 13123(line=535, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push_check (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp149) ;
// ATSlocal_void (tmp150) ;
// ATSlocal_void (tmp151) ;
ATSlocal (ats_bool_type, tmp152) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push_check:
/* tmp150 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push (arg0) ;
/* tmp151 = ats_selsin_mac(tmp150, atslab_1) */ ;
tmp152 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_isnot_dummy (arg0) ;
if (tmp152) {
tmp149 = filename_occurs_34 (arg0) ;
} else {
tmp149 = ats_false_bool ;
} /* end of [if] */
return (tmp149) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_filenamelst_push_check] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 13217(line=540, offs=7) -- 13542(line=551, offs=35)
*/
ATSstaticdec()
ats_void_type
loop_42 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
// ATSlocal_void (tmp157) ;
// ATSlocal_void (tmp158) ;
ATSlocal (ats_ptr_type, tmp159) ;

__ats_lab_loop_42:
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp155 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
tmp156 = &ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_1) ;
/* tmp157 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full (arg0, tmp155) ;
/* tmp158 = */ atspre_fprint_newline (arg0) ;
tmp159 = ats_ptrget_mac(ats_ptr_type, tmp156) ;
arg0 = arg0 ;
arg1 = tmp159 ;
goto __ats_lab_loop_42 ; // tail call
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
break ;
} while (0) ;
return /* (tmp154) */ ;
} /* end of [loop_42] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 13199(line=539, offs=3) -- 13657(line=556, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_the_filenamelst (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp153) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_ptr_type, tmp161) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_the_filenamelst:
tmp160 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp127), atslab_1) ;
tmp161 = ats_ptrget_mac(ats_ptr_type, tmp160) ;
/* tmp153 = */ loop_42 (arg0, tmp161) ;
return /* (tmp153) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_the_filenamelst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14004(line=574, offs=5) -- 14150(line=579, offs=2)
*/
ATSstaticdec()
ats_ptr_type
the_pathlst_get_43 () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
ATSlocal (ats_ptr_type, tmp168) ;
ATSlocal (ats_ptr_type, tmp169) ;

__ats_lab_the_pathlst_get_43:
tmp167 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp162), atslab_1) ;
tmp168 = ats_ptrget_mac(ats_ptr_type, tmp167) ;
tmp169 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, tmp167) = tmp169 ;
tmp166 = tmp168 ;
return (tmp166) ;
} /* end of [the_pathlst_get_43] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14184(line=581, offs=5) -- 14330(line=586, offs=2)
*/
ATSstaticdec()
ats_void_type
the_pathlst_set_44 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp170) ;
ATSlocal (ats_ptr_type, tmp171) ;
ATSlocal (ats_ptr_type, tmp172) ;

__ats_lab_the_pathlst_set_44:
tmp171 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp162), atslab_1) ;
tmp172 = ats_ptrget_mac(ats_ptr_type, tmp171) ;
if (tmp172 != (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_filename.dats: 14288(line=584, offs=7) -- 14308(line=584, offs=27)") ; }
ats_ptrget_mac(ats_ptr_type, tmp171) = arg0 ;
return /* (tmp170) */ ;
} /* end of [the_pathlst_set_44] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14388(line=590, offs=3) -- 14538(line=595, offs=2)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_pop () {
/* local vardec */
// ATSlocal_void (tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_ptr_type, tmp176) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_pop:
tmp174 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp162), atslab_1) ;
tmp175 = ats_ptrget_mac(ats_ptr_type, tmp174) ;
if (tmp175 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_filename.dats: 14490(line=593, offs=7) -- 14516(line=593, offs=33)") ; }
tmp176 = ats_caselptrlab_mac(anairiats_sum_2, tmp175, atslab_1) ;
ATS_FREE(tmp175) ;
ats_ptrget_mac(ats_ptr_type, tmp174) = tmp176 ;
return /* (tmp173) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_pop] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14595(line=598, offs=18) -- 14661(line=600, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_push (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp177) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_push:
/* tmp177 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_ppush (arg0) ;
return /* (tmp177) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_push] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14720(line=603, offs=19) -- 14818(line=607, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_ppush (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp178) ;
ATSlocal (ats_ptr_type, tmp179) ;
ATSlocal (ats_ptr_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_ppush:
tmp179 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp162), atslab_1) ;
tmp181 = ats_ptrget_mac(ats_ptr_type, tmp179) ;
tmp180 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp180, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_2, tmp180, atslab_1, tmp181) ;
ats_ptrget_mac(ats_ptr_type, tmp179) = tmp180 ;
return /* (tmp178) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_pathlst_ppush] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 14875(line=611, offs=5) -- 15027(line=616, offs=2)
*/
ATSstaticdec()
ats_ptr_type
the_prepathlst_get_48 () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp182) ;
ATSlocal (ats_ptr_type, tmp183) ;
ATSlocal (ats_ptr_type, tmp184) ;
ATSlocal (ats_ptr_type, tmp185) ;

__ats_lab_the_prepathlst_get_48:
tmp183 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp164), atslab_1) ;
tmp184 = ats_ptrget_mac(ats_ptr_type, tmp183) ;
tmp185 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, tmp183) = tmp185 ;
tmp182 = tmp184 ;
return (tmp182) ;
} /* end of [the_prepathlst_get_48] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 15064(line=618, offs=5) -- 15216(line=623, offs=2)
*/
ATSstaticdec()
ats_void_type
the_prepathlst_set_49 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp186) ;
ATSlocal (ats_ptr_type, tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;

__ats_lab_the_prepathlst_set_49:
tmp187 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp164), atslab_1) ;
tmp188 = ats_ptrget_mac(ats_ptr_type, tmp187) ;
if (tmp188 != (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_filename.dats: 15174(line=621, offs=7) -- 15194(line=621, offs=27)") ; }
ats_ptrget_mac(ats_ptr_type, tmp187) = arg0 ;
return /* (tmp186) */ ;
} /* end of [the_prepathlst_set_49] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 15279(line=626, offs=21) -- 15380(line=630, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_prepathlst_push (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_ptr_type, tmp191) ;
ATSlocal (ats_ptr_type, tmp192) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_prepathlst_push:
tmp190 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp164), atslab_1) ;
tmp192 = ats_ptrget_mac(ats_ptr_type, tmp190) ;
tmp191 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp191, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_2, tmp191, atslab_1, tmp192) ;
ats_ptrget_mac(ats_ptr_type, tmp190) = tmp191 ;
return /* (tmp189) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__the_prepathlst_push] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 15482(line=638, offs=1) -- 15655(line=647, offs=6)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp193) ;
ATSlocal (ats_ptr_type, tmp194) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make:
tmp194 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_make_string (arg2) ;
tmp193 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp193, atslab_filename_givename, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp193, atslab_filename_partname, arg1) ;
ats_selptrset_mac(anairiats_rec_1, tmp193, atslab_filename_fullname, tmp194) ;

return (tmp193) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 15828(line=659, offs=1) -- 16395(line=681, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_local_52 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp195) ;
ATSlocal (ats_ptr_type, tmp196) ;
ATSlocal (ats_ptr_type, tmp197) ;
ATSlocal (ats_ptr_type, tmp198) ;
ATSlocal (ats_ptr_type, tmp199) ;
// ATSlocal_void (tmp200) ;
ATSlocal (ats_bool_type, tmp201) ;
// ATSlocal_void (tmp202) ;

__ats_lab_aux_local_52:
tmp196 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_current () ;
tmp197 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_get_partname (tmp196) ;
tmp198 = patsopt_filename_merge (tmp197, arg0) ;
tmp199 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__path_normalize_vt (ats_castfn_mac(ats_ptr_type, tmp198)) ;
/* tmp200 = */ atspre_strptr_free (tmp198) ;
tmp201 = atspre_test_file_exists (ats_castfn_mac(ats_ptr_type, tmp199)) ;
if (tmp201) {
tmp195 = ats_castfn_mac(ats_ptr_type, tmp199) ;
} else {
/* tmp202 = */ atspre_strptr_free (tmp199) ;
tmp195 = atspre_stropt_none ;
} /* end of [if] */
return (tmp195) ;
} /* end of [aux_local_52] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 16444(line=686, offs=1) -- 16651(line=699, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_try_53 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp203) ;
ATSlocal (ats_ptr_type, tmp204) ;
ATSlocal (ats_ptr_type, tmp205) ;

__ats_lab_aux_try_53:
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp204 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp205 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp203 = aux2_try_54 (tmp204, tmp205, arg1) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_14_1:
tmp203 = atspre_stropt_none ;
break ;
} while (0) ;
return (tmp203) ;
} /* end of [aux_try_53] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 16677(line=701, offs=5) -- 17119(line=721, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux2_try_54 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp206) ;
ATSlocal (ats_ptr_type, tmp207) ;
ATSlocal (ats_bool_type, tmp208) ;
// ATSlocal_void (tmp209) ;

__ats_lab_aux2_try_54:
tmp207 = patsopt_filename_append (arg0, arg2) ;
tmp208 = atspre_test_file_exists (ats_castfn_mac(ats_ptr_type, tmp207)) ;
if (tmp208) {
tmp206 = ats_castfn_mac(ats_ptr_type, tmp207) ;
} else {
/* tmp209 = */ atspre_strptr_free (tmp207) ;
tmp206 = aux_try_53 (arg1, arg2) ;
} /* end of [if] */
return (tmp206) ;
} /* end of [aux2_try_54] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 17167(line=725, offs=5) -- 17455(line=735, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_try_pathlst_55 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp210) ;
ATSlocal (ats_ptr_type, tmp211) ;
ATSlocal (ats_ptr_type, tmp212) ;
ATSlocal (ats_ptr_type, tmp213) ;
// ATSlocal_void (tmp214) ;

__ats_lab_aux_try_pathlst_55:
tmp211 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__theCurDir_get () ;
tmp212 = the_pathlst_get_43 () ;
tmp213 = aux2_try_54 (tmp211, ats_castfn_mac(ats_ptr_type, tmp212), arg0) ;
/* tmp214 = */ the_pathlst_set_44 (tmp212) ;
tmp210 = tmp213 ;
return (tmp210) ;
} /* end of [aux_try_pathlst_55] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 17489(line=737, offs=5) -- 17689(line=745, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_try_prepathlst_56 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp215) ;
ATSlocal (ats_ptr_type, tmp216) ;
ATSlocal (ats_ptr_type, tmp217) ;
// ATSlocal_void (tmp218) ;

__ats_lab_aux_try_prepathlst_56:
tmp216 = the_prepathlst_get_48 () ;
tmp217 = aux_try_53 (ats_castfn_mac(ats_ptr_type, tmp216), arg0) ;
/* tmp218 = */ the_prepathlst_set_49 (tmp216) ;
tmp215 = tmp217 ;
return (tmp215) ;
} /* end of [aux_try_prepathlst_56] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 17747(line=750, offs=1) -- 18075(line=768, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_relative_57 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp219) ;
ATSlocal (ats_int_type, tmp220) ;
ATSlocal (ats_ptr_type, tmp221) ;
ATSlocal (ats_bool_type, tmp222) ;

__ats_lab_aux_relative_57:
tmp220 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_srchknd (ats_castfn_mac(ats_ptr_type, arg0)) ;
do {
/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (tmp220 != 0) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp219 = aux_local_52 (ats_castfn_mac(ats_ptr_type, arg0)) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
__ats_lab_16_1:
tmp221 = aux_try_pathlst_55 (ats_castfn_mac(ats_ptr_type, arg0)) ;
tmp222 = atspre_stropt_is_some (tmp221) ;
if (tmp222) {
tmp219 = tmp221 ;
} else {
tmp219 = aux_try_prepathlst_56 (ats_castfn_mac(ats_ptr_type, arg0)) ;
} /* end of [if] */
break ;
} while (0) ;
return (tmp219) ;
} /* end of [aux_relative_57] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 18161(line=774, offs=3) -- 18448(line=788, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_local (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp223) ;
ATSlocal (ats_ptr_type, tmp224) ;
ATSlocal (ats_bool_type, tmp225) ;
ATSlocal (ats_ptr_type, tmp226) ;
ATSlocal (ats_ptr_type, tmp227) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_local:
tmp224 = aux_local_52 (arg0) ;
tmp225 = atspre_stropt_is_some (tmp224) ;
if (tmp225) {
tmp226 = partname_fullize_31 (ats_castfn_mac(ats_ptr_type, tmp224)) ;
tmp227 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make (arg0, ats_castfn_mac(ats_ptr_type, tmp224), tmp226) ;
tmp223 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp223, atslab_0, tmp227) ;
} else {
tmp223 = (ats_sum_ptr_type)0 ;
} /* end of [if] */
return (tmp223) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_local] */

/*
// /home/hwxi/research/Postiats/git/src/pats_filename.dats: 18544(line=794, offs=3) -- 19398(line=832, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_relative (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp228) ;
ATSlocal (ats_int_type, tmp229) ;
ATSlocal (ats_ptr_type, tmp230) ;
ATSlocal (ats_ptr_type, tmp231) ;
ATSlocal (ats_bool_type, tmp232) ;
ATSlocal (ats_bool_type, tmp233) ;
ATSlocal (ats_bool_type, tmp234) ;
ATSlocal (ats_ptr_type, tmp235) ;
ATSlocal (ats_ptr_type, tmp236) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_relative:
tmp229 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__givename_get_ngurl (arg0) ;
tmp230 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__pkgsrcname_relocatize (arg0, tmp229) ;
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
__ats_lab_17_1:
tmp232 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__givename_is_relative (tmp230) ;
if (!tmp232) { goto __ats_lab_18_1 ; }
tmp231 = aux_relative_57 (tmp230) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
tmp233 = atspre_test_file_exists (tmp230) ;
if (tmp233) {
tmp231 = ats_castfn_mac(ats_ptr_type, tmp230) ;
} else {
tmp231 = atspre_stropt_none ;
} /* end of [if] */
break ;
} while (0) ;
tmp234 = atspre_stropt_is_some (tmp231) ;
if (tmp234) {
tmp235 = partname_fullize_31 (ats_castfn_mac(ats_ptr_type, tmp231)) ;
tmp236 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_make (arg0, ats_castfn_mac(ats_ptr_type, tmp231), tmp235) ;
tmp228 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
ats_selptrset_mac(anairiats_sum_3, tmp228, atslab_0, tmp236) ;
} else {
tmp228 = (ats_sum_ptr_type)0 ;
} /* end of [if] */
return (tmp228) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filenameopt_make_relative] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2unsafe_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2libc_2SATS_2string_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e11_2libc_2SATS_2unistd_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2unsafe_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__staload () ;
ATS_2d0_2e2_2e11_2libc_2SATS_2string_2esats__staload () ;
ATS_2d0_2e2_2e11_2libc_2SATS_2unistd_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp56, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp57, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp123, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp127, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp128, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp162, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp163, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp164, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp165, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp56 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp56, atslab_filename_givename, ATSstrcst("")) ;
ats_selptrset_mac(anairiats_rec_1, statmp56, atslab_filename_partname, ATSstrcst("")) ;
ats_selptrset_mac(anairiats_rec_1, statmp56, atslab_filename_fullname, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_dummy, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_dummy = statmp56 ;
statmp57 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp57, atslab_filename_givename, ATSstrcst("__STDIN__")) ;
ats_selptrset_mac(anairiats_rec_1, statmp57, atslab_filename_partname, ATSstrcst("__STDIN__")) ;
ats_selptrset_mac(anairiats_rec_1, statmp57, atslab_filename_fullname, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_stdin, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_stdin = statmp57 ;
statmp123 = ref_make_elt_01088_ats_ptr_type (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__filename_dummy) ;
statmp128 = (ats_sum_ptr_type)0 ;
statmp127 = ref_make_elt_01088_ats_ptr_type (statmp128) ;
statmp163 = (ats_sum_ptr_type)0 ;
statmp162 = ref_make_elt_01088_ats_ptr_type (statmp163) ;
statmp165 = (ats_sum_ptr_type)0 ;
statmp164 = ref_make_elt_01088_ats_ptr_type (statmp165) ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */


ats_ptr_type
patsopt_filename_merge (
  ats_ptr_type ful, ats_ptr_type bas
) {
  char c, dirsep ;
  char *p0, *p1, *p ;
  int n, n1, n2, found = 0 ;
  char *fulbas ;
  p0 = p = (char*)ful ;
  dirsep =
    patsopt_filename_theDirSep_get () ;
//
  while (1) {
    c = *p++ ;
    if (c == 0) break ;
    if (c == dirsep) { found = 1 ; p1 = p ; }
  }
//
  n1 = 0 ;
  if (found) n1 = (p1-p0) ;
  n2 = strlen ((char*)bas) ;
  n = n1 + n2 ;
  fulbas = ATS_MALLOC (n+1) ;
  memcpy (fulbas, ful, n1) ;
  memcpy (fulbas + n1, bas, n2) ;
  fulbas[n] = '\000' ;
//
  return fulbas ;
//
} // end of [patsopt_filename_merge]

ats_ptr_type
patsopt_filename_append (
  ats_ptr_type dir, ats_ptr_type bas
) {
  int n1, n2, n ;
  char dirsep, *dirbas ;
//
  dirsep = patsopt_filename_theDirSep_get () ;
//
  n1 = strlen ((char*)dir) ;
  n2 = strlen ((char*)bas) ;
  n = n1 + n2 ;
//
  if (n1 > 0 && ((char*)dir)[n1-1] != dirsep) n += 1 ;
  dirbas = ATS_MALLOC (n + 1) ;
  memcpy (dirbas, dir, n1) ;
  if (n > n1 + n2) { dirbas[n1] = dirsep ; n1 += 1 ; }
  memcpy (dirbas + n1, bas, n2) ;
  dirbas[n] = '\000' ;
//
  return dirbas ;
} /* end of [patsopt_filename_append] */



/* ****** ****** */

/* end of [pats_filename_dats.c] */
