/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2016-7-23: 10h:20m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_tokbuf.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/stdio.cats"

#include "libc/sys/CATS/types.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_0 ;

typedef struct {
ats_char_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
ats_lint_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
} anairiats_sum_3 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__PSM_0) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_bool_type, atspre_neg_bool) (ats_bool_type) ;
ATSextern_fun(ats_char_type, atspre_char_of_int) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_lint_type, atspre_succ_lint) (ats_lint_type) ;
ATSextern_fun(ats_bool_type, atspre_gte_lint_lint) (ats_lint_type, ats_lint_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_lint) (ats_ptr_type, ats_lint_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_succ_size1) (ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_strbufptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_char_type, atspre_string_get_char_at) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_make_list_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_ptr_type, atspre_string_make_list_rev_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_string_isnot_atend) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_lint_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_location_2esats__location_beg_ntot) (ats_ptr_type) ;
ATSextern_fun(ats_lint_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_location_2esats__location_end_ntot) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__lexbufobj_make_string) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__test_prfkind) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__funkind_is_proof) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_basics_2esats__valkind_is_proof) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__token_get_loc) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__token_is_comment) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__token_is_extcode) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__token_is_keyword) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__lexbufobj_get_tokenlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__tokbufobj_make_lexbufobj) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__tokbufobj_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__tokbufobj_unget_token) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__fprint_synmark) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__listize_token2psynmark) (ats_ptr_type) ;
ATSextern_fun(anairiats_rec_0, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__psynmarklst_split) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__tokbufobj_get_psynmarklst) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__psynmark_process_xhtml_embedded) (ats_ptr_type, ats_clo_ref_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__fhtml_putc) (ats_char_type, ats_clo_ref_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__fstring_putc) (ats_ptr_type, ats_clo_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__lexbufobj_level1_psynmarkize) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_parsing_2esats__parse_from_tokbuf_toplevel) (ats_int_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0rt_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__e0xp_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0exp_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0explst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0expopt_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__labs0explst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__e0fftaglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__e0fftaglstopt_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__p0at_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__p0atlst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__p0atopt_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__p0atlst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__labp0at_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__labp0atlst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0exp_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0explst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0expopt_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0explst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__labd0explst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__t0mpmarglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__gm0atlst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__guap0at_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__c0laulst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__q0marglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__a0msrtlst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0expdeflst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__e0xndeclst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0atconlst_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0atdeclst_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__a0typlst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__a0typlst_npf_mark) (ats_int_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0cstarglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0cstdeclst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0arglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0vararglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__s0marglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__m0acarglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__m0acdeflst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__f0arglst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__witht0ype_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__f0undeclst_mark) (ats_ptr_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__v0aldeclst_mark) (ats_ptr_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__v0ardeclst_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__i0mparg_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__impqi0de_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__i0mpdec_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0ecl_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__d0eclist_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__guad0ecl_mark) (ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__guad0ecln_mark) (ats_ptr_type, ats_ref_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type psynmark_process_02456_ (ats_ptr_type arg0, ats_clo_ref_type arg1) ;
static
ats_ptr_type ptr0_get_02491_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type ptrget_02495_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type ptr0_set_02492_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type ptrset_02496_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_int_type __ats_fun_3 (ats_ptr_type env0, ats_char_type arg0) ;
static
ats_clo_ptr_type __ats_fun_3_closure_make (ats_ptr_type env0) ;
static
ats_int_type __ats_fun_3_clofun (ats_clo_ptr_type cloptr, ats_char_type arg0) ;
static
ats_void_type psynmarklst_process_02459_ (ats_lint_type arg0, ats_ref_type arg1, ats_clo_ref_type arg2) ;
static
ats_void_type psynmarklstlst_process_02460_ (ats_lint_type arg0, ats_ref_type arg1, ats_clo_ref_type arg2) ;
static
ats_void_type loop_9 (ats_ptr_type arg0, ats_size_type arg1, ats_ref_type arg2, ats_clo_ref_type arg3, ats_ref_type arg4) ;
static
ats_void_type loop_13 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type loop_13_closure_make (ats_ptr_type env0) ;
static
ats_void_type loop_13_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_fun_01500_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_16 (ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type __ats_fun_14 (ats_ref_type arg0) ;
static
ats_void_type string_psynmarklstlst_process_02463_ (ats_ptr_type arg0, ats_ptr_type arg1, ats_clo_ref_type arg2) ;
static
ats_int_type loop_18 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type list_length_01410_ats_char_type (ats_ptr_type arg0) ;
static
ats_void_type loop_20 (ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_01499_ats_char_type (ats_ptr_type arg0) ;
static
ats_ptr_type string_pats2xhtmlize_02467_ (ats_int_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type charlst_pats2xhtmlize_02468_ (ats_int_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml_embedded.dats: 491(line=32, offs=20) -- 550(line=33, offs=46)
*/
ATSstaticdec()
ats_void_type
psynmark_process_02456_ (ats_ptr_type arg0, ats_clo_ref_type arg1) {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_psynmark_process_02456_:
/* tmp0 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__psynmark_process_xhtml_embedded (arg0, arg1) ;
return /* (tmp0) */ ;
} /* end of [psynmark_process_02456_] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/unsafe.dats: 1763(line=50, offs=10) -- 1979(line=60, offs=2)
*/
ATSstaticdec()
ats_ptr_type
ptr0_get_02491_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;

__ats_lab_ptr0_get_02491_ats_ptr_type:
tmp9 = ats_ptrget_mac(ats_ptr_type, ats_castfn_mac(ats_ptr_type, arg0)) ;
return (tmp9) ;
} /* end of [ptr0_get_02491_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/unsafe.dats: 2430(line=82, offs=21) -- 2450(line=82, offs=41)
*/
ATSstaticdec()
ats_ptr_type
ptrget_02495_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab_ptrget_02495_ats_ptr_type:
tmp8 = ptr0_get_02491_ats_ptr_type (arg0) ;
return (tmp8) ;
} /* end of [ptrget_02495_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/unsafe.dats: 2024(line=63, offs=10) -- 2250(line=73, offs=2)
*/
ATSstaticdec()
ats_void_type
ptr0_set_02492_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp12) ;

__ats_lab_ptr0_set_02492_ats_ptr_type:
ats_ptrget_mac(ats_ptr_type, ats_castfn_mac(ats_ptr_type, arg0)) = arg1 ;
return /* (tmp12) */ ;
} /* end of [ptr0_set_02492_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/unsafe.dats: 2472(line=83, offs=21) -- 2499(line=83, offs=48)
*/
ATSstaticdec()
ats_void_type
ptrset_02496_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp11) ;

__ats_lab_ptrset_02496_ats_ptr_type:
/* tmp11 = */ ptr0_set_02492_ats_ptr_type (arg0, arg1) ;
return /* (tmp11) */ ;
} /* end of [ptrset_02496_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml.dats: 4637(line=203, offs=12) -- 4811(line=211, offs=4)
*/
ATSstaticdec()
ats_int_type
__ats_fun_3 (ats_ptr_type env0, ats_char_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
// ATSlocal_void (tmp10) ;
ATSlocal (ats_ptr_type, tmp13) ;

__ats_lab___ats_fun_3:
tmp7 = ptrget_02495_ats_ptr_type (env0) ;
tmp13 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp13, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_1, tmp13, atslab_1, tmp7) ;
/* tmp10 = */ ptrset_02496_ats_ptr_type (env0, tmp13) ;
tmp6 = 0 ;
return (tmp6) ;
} /* end of [__ats_fun_3] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} __ats_fun_3_closure_type ;

ats_int_type
__ats_fun_3_clofun (ats_clo_ptr_type cloptr, ats_char_type arg0) {
return __ats_fun_3 (((__ats_fun_3_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_3_closure_init (__ats_fun_3_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_3_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
__ats_fun_3_closure_make (ats_ptr_type env0) {
__ats_fun_3_closure_type *p_clo = ATS_MALLOC(sizeof(__ats_fun_3_closure_type)) ;
__ats_fun_3_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 37171(line=1660, offs=3) -- 37646(line=1680, offs=4)
*/
ATSstaticdec()
ats_void_type
psynmarklst_process_02459_ (ats_lint_type arg0, ats_ref_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_lint_type, tmp26) ;
ATSlocal (ats_bool_type, tmp27) ;
// ATSlocal_void (tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;

__ats_lab_psynmarklst_process_02459_:
do {
/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (ats_ptrget_mac(ats_ptr_type, arg1) == (ats_sum_ptr_type)0) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp24 = ats_caselptrlab_mac(anairiats_sum_2, ats_ptrget_mac(ats_ptr_type, arg1), atslab_0) ;
tmp25 = &ats_caselptrlab_mac(anairiats_sum_2, ats_ptrget_mac(ats_ptr_type, arg1), atslab_1) ;

tmp26 = ats_caselptrlab_mac(anairiats_sum_3, tmp24, atslab_0) ;
tmp27 = atspre_gte_lint_lint (arg0, tmp26) ;
if (tmp27) {
/* tmp28 = */ psynmark_process_02456_ (tmp24, arg2) ;
tmp29 = ats_ptrget_mac(ats_ptr_type, tmp25) ;
ATS_FREE(ats_ptrget_mac(ats_ptr_type, arg1)) ;
ats_ptrget_mac(ats_ptr_type, arg1) = tmp29 ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = arg2 ;
goto __ats_lab_psynmarklst_process_02459_ ; // tail call
} else {
/* empty */
} /* end of [if] */
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
// if (ats_ptrget_mac(ats_ptr_type, arg1) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_2_1:
break ;
} while (0) ;
return /* (tmp23) */ ;
} /* end of [psynmarklst_process_02459_] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 37717(line=1684, offs=3) -- 38033(line=1695, offs=43)
*/
ATSstaticdec()
ats_void_type
psynmarklstlst_process_02460_ (ats_lint_type arg0, ats_ref_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
// ATSlocal_void (tmp22) ;

__ats_lab_psynmarklstlst_process_02460_:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (ats_ptrget_mac(ats_ptr_type, arg1) == (ats_sum_ptr_type)0) { goto __ats_lab_3_0 ; }
__ats_lab_0_1:
tmp20 = &ats_caselptrlab_mac(anairiats_sum_2, ats_ptrget_mac(ats_ptr_type, arg1), atslab_0) ;
tmp21 = &ats_caselptrlab_mac(anairiats_sum_2, ats_ptrget_mac(ats_ptr_type, arg1), atslab_1) ;
/* tmp22 = */ psynmarklst_process_02459_ (arg0, tmp20, arg2) ;
arg0 = arg0 ;
arg1 = tmp21 ;
arg2 = arg2 ;
goto __ats_lab_psynmarklstlst_process_02460_ ; // tail call
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (ats_ptrget_mac(ats_ptr_type, arg1) != (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 37743(line=1686, offs=3) -- 38033(line=1695, offs=43)") ; }
__ats_lab_3_1:
break ;
} while (0) ;
return /* (tmp19) */ ;
} /* end of [psynmarklstlst_process_02460_] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 38367(line=1719, offs=1) -- 38843(line=1744, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_9 (ats_ptr_type arg0, ats_size_type arg1, ats_ref_type arg2, ats_clo_ref_type arg3, ats_ref_type arg4) {
/* local vardec */
// ATSlocal_void (tmp17) ;
// ATSlocal_void (tmp18) ;
ATSlocal (ats_bool_type, tmp30) ;
ATSlocal (ats_char_type, tmp31) ;
ATSlocal (ats_lint_type, tmp32) ;
ATSlocal (ats_int_type, tmp33) ;
ATSlocal (ats_size_type, tmp34) ;

__ats_lab_loop_9:
/* tmp18 = */ psynmarklstlst_process_02460_ (ats_ptrget_mac(ats_lint_type, arg4), arg2, arg3) ;
tmp30 = atspre_string_isnot_atend (arg0, arg1) ;
if (tmp30) {
tmp31 = atspre_string_get_char_at (arg0, arg1) ;
tmp32 = atspre_succ_lint (ats_ptrget_mac(ats_lint_type, arg4)) ;
ats_ptrget_mac(ats_lint_type, arg4) = tmp32 ;
tmp33 = _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__fhtml_putc (tmp31, arg3) ;
tmp34 = atspre_succ_size1 (arg1) ;
arg0 = arg0 ;
arg1 = tmp34 ;
arg2 = arg2 ;
arg3 = arg3 ;
arg4 = arg4 ;
goto __ats_lab_loop_9 ; // tail call
} else {
/* empty */
} /* end of [if] */
return /* (tmp17) */ ;
} /* end of [loop_9] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 5132(line=186, offs=7) -- 5320(line=191, offs=28)
*/
ATSstaticdec()
ats_void_type
loop_13 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
// ATSlocal_void (tmp42) ;

__ats_lab_loop_13:
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp40 = &ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp41 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
/* tmp42 = */ ((ats_void_type(*)(ats_ref_type))env0) (tmp40) ;
ATS_FREE(arg0) ;
arg0 = tmp41 ;
goto __ats_lab_loop_13 ; // tail call
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_5_1:
break ;
} while (0) ;
return /* (tmp39) */ ;
} /* end of [loop_13] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} loop_13_closure_type ;

ats_void_type
loop_13_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
loop_13 (((loop_13_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
loop_13_closure_init (loop_13_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&loop_13_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
loop_13_closure_make (ats_ptr_type env0) {
loop_13_closure_type *p_clo = ATS_MALLOC(sizeof(loop_13_closure_type)) ;
loop_13_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 5111(line=185, offs=18) -- 5359(line=195, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_fun_01500_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp38) ;

__ats_lab_list_vt_free_fun_01500_ats_ptr_type:
/* tmp38 = */ loop_13 (arg1, arg0) ;
return /* (tmp38) */ ;
} /* end of [list_vt_free_fun_01500_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4893(line=177, offs=7) -- 5015(line=178, offs=73)
*/
ATSstaticdec()
ats_void_type
loop_16 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab_loop_16:
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp46 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp46 ;
goto __ats_lab_loop_16 ; // tail call
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_7_1:
break ;
} while (0) ;
return /* (tmp45) */ ;
} /* end of [loop_16] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4875(line=176, offs=14) -- 5054(line=182, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp44) ;

__ats_lab_list_vt_free_01499_ats_ptr_type:
/* tmp44 = */ loop_16 (arg0) ;
return /* (tmp44) */ ;
} /* end of [list_vt_free_01499_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 39038(line=1756, offs=36) -- 39063(line=1756, offs=61)
*/
ATSstaticdec()
ats_void_type
__ats_fun_14 (ats_ref_type arg0) {
/* local vardec */
// ATSlocal_void (tmp43) ;

__ats_lab___ats_fun_14:
/* tmp43 = */ list_vt_free_01499_ats_ptr_type (ats_ptrget_mac(ats_ptr_type, arg0)) ;
return /* (tmp43) */ ;
} /* end of [__ats_fun_14] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_psynmark.dats: 38289(line=1713, offs=3) -- 39087(line=1760, offs=4)
*/
ATSstaticdec()
ats_void_type
string_psynmarklstlst_process_02463_ (ats_ptr_type arg0, ats_ptr_type arg1, ats_clo_ref_type arg2) {
/* local vardec */
// ATSlocal_void (tmp16) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_lint_type, tmp36) ;
// ATSlocal_void (tmp37) ;

__ats_lab_string_psynmarklstlst_process_02463_:
/* ats_ptr_type tmp35 ; */
tmp35 = arg1 ;
/* ats_lint_type tmp36 ; */
tmp36 = 0L ;
/* tmp37 = */ loop_9 (ats_castfn_mac(ats_ptr_type, arg0), 0, (&tmp35), arg2, (&tmp36)) ;
/* tmp16 = */ list_vt_free_fun_01500_ats_ptr_type (tmp35, &__ats_fun_14) ;
return /* (tmp16) */ ;
} /* end of [string_psynmarklstlst_process_02463_] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 51781(line=1842, offs=7) -- 51921(line=1845, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_18 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_int_type, tmp52) ;

__ats_lab_loop_18:
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp51 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp52 = atspre_isucc (arg1) ;
arg0 = tmp51 ;
arg1 = tmp52 ;
goto __ats_lab_loop_18 ; // tail call
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_9_1:
tmp50 = arg1 ;
break ;
} while (0) ;
return (tmp50) ;
} /* end of [loop_18] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list.dats: 51764(line=1841, offs=13) -- 52005(line=1849, offs=4)
*/
ATSstaticdec()
ats_int_type
list_length_01410_ats_char_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp49) ;

__ats_lab_list_length_01410_ats_char_type:
tmp49 = loop_18 (arg0, 0) ;
return (tmp49) ;
} /* end of [list_length_01410_ats_char_type] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4893(line=177, offs=7) -- 5015(line=178, offs=73)
*/
ATSstaticdec()
ats_void_type
loop_20 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;

__ats_lab_loop_20:
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp57 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp57 ;
goto __ats_lab_loop_20 ; // tail call
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
break ;
} while (0) ;
return /* (tmp56) */ ;
} /* end of [loop_20] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4875(line=176, offs=14) -- 5054(line=182, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_01499_ats_char_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp55) ;

__ats_lab_list_vt_free_01499_ats_char_type:
/* tmp55 = */ loop_20 (arg0) ;
return /* (tmp55) */ ;
} /* end of [list_vt_free_01499_ats_char_type] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml.dats: 4370(line=190, offs=3) -- 5119(line=226, offs=4)
*/
ATSstaticdec()
ats_ptr_type
string_pats2xhtmlize_02467_ (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp14) ;
// ATSlocal_void (tmp15) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_int_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp53) ;
// ATSlocal_void (tmp54) ;

__ats_lab_string_pats2xhtmlize_02467_:
tmp3 = _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__lexbufobj_make_string (arg1) ;
tmp4 = _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__lexbufobj_level1_psynmarkize (arg0, tmp3) ;
/* ats_ptr_type tmp5 ; */
tmp5 = (ats_sum_ptr_type)0 ;
tmp14 = __ats_fun_3_closure_make ((&tmp5)) ;
/* tmp15 = */ string_psynmarklstlst_process_02463_ (arg1, tmp4, tmp14) ;
tmp47 = ats_castfn_mac(ats_ptr_type, tmp5) ;
tmp48 = list_length_01410_ats_char_type (tmp47) ;
tmp53 = atspre_string_make_list_rev_int (tmp47, tmp48) ;
/* tmp54 = */ list_vt_free_01499_ats_char_type (tmp5) ;
tmp2 = ats_castfn_mac(ats_ptr_type, tmp53) ;
return (tmp2) ;
} /* end of [string_pats2xhtmlize_02467_] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml_embedded.dats: 647(line=40, offs=3) -- 703(line=40, offs=59)
*/
ATSglobaldec()
ats_ptr_type
libatsynmark_string_pats2xhtmlize_embedded (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab_libatsynmark_string_pats2xhtmlize_embedded:
tmp1 = string_pats2xhtmlize_02467_ (arg0, arg1) ;
return (tmp1) ;
} /* end of [libatsynmark_string_pats2xhtmlize_embedded] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml.dats: 5211(line=232, offs=3) -- 5439(line=240, offs=4)
*/
ATSstaticdec()
ats_ptr_type
charlst_pats2xhtmlize_02468_ (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_int_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
// ATSlocal_void (tmp63) ;

__ats_lab_charlst_pats2xhtmlize_02468_:
tmp60 = list_length_01410_ats_char_type (arg1) ;
tmp61 = atspre_string_make_list_int (arg1, tmp60) ;
tmp62 = string_pats2xhtmlize_02467_ (arg0, ats_castfn_mac(ats_ptr_type, tmp61)) ;
/* tmp63 = */ atspre_strbufptr_free (tmp61) ;
tmp59 = tmp62 ;
return (tmp59) ;
} /* end of [charlst_pats2xhtmlize_02468_] */

/*
// /home/hwxi/Research/ATS-Postiats/utils/libatsynmark/DATS/libatsynmark_pats2xhtml_embedded.dats: 790(line=45, offs=3) -- 847(line=45, offs=60)
*/
ATSglobaldec()
ats_ptr_type
libatsynmark_charlst_pats2xhtmlize_embedded (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp58) ;

__ats_lab_libatsynmark_charlst_pats2xhtmlize_embedded:
tmp58 = charlst_pats2xhtmlize_02468_ (arg0, arg1) ;
return (tmp58) ;
} /* end of [libatsynmark_charlst_pats2xhtmlize_embedded] */

/* static load function */

extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_2edats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__staload_flag = 1 ;

_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2SATS_2libatsynmark_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_psynmark_2edats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_2edats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
// extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__dynload () {
// _2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2utils_2libatsynmark_2DATS_2libatsynmark_pats2xhtml_embedded_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [libatsynmark_pats2xhtml_embedded_dats.c] */
